changelog:
  exclude:
    labels:
      - "dependencies"
      - "skip-changelog"
    authors:
      - "dependabot"
      - "dependabot[bot]"
  categories:
    - title: "New features"
      labels:
        - "enhancement"
        - "new-game-type"
    - title: "Bug fixes"
      labels:
        - "bug"
    - title: "Security"
      labels:
        - "security"
    - title: "Documentation"
      labels:
        - "documentation"
    - title: "Infrastructure & CI"
      labels:
        - "ci"
        - "infrastructure"
    - title: "Other changes"
      labels:
        - "*"
