services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: fabdoyoumeme-${STAGE:-dev}-mailpit
    restart: unless-stopped
    ports:
      - '8025:8025'
    expose:
      - 1025
    networks:
      - project_network

  backend:
    build: ../backend
    environment:
      SMTP_HOST: mailpit
      SMTP_PORT: '1025'
      SMTP_USERNAME: ''
      SMTP_PASSWORD: ''
      SMTP_FROM: noreply@fabdoyoumeme.local
      LOG_LEVEL: debug

  frontend:
    build: ../frontend
    ports:
      - '3000:3000'

  postgres:
    ports:
      - '5432:5432'
