services:
  backend:
    image: ghcr.io/morgankryze/fabdoyoumeme-backend:stable

  frontend:
    image: ghcr.io/morgankryze/fabdoyoumeme-frontend:stable
    networks:
      - project_network
      - pangolin

networks:
  pangolin:
    external: true
