services:
  backend:
    image: ghcr.io/morgankryze/fabyoumeme-backend:latest

  frontend:
    image: ghcr.io/morgankryze/fabyoumeme-frontend:latest
    networks:
      - project_network
      - pangolin

networks:
  pangolin:
    external: true
