// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: admin_notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM admin_notifications WHERE read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminNotification = `-- name: CreateAdminNotification :one

INSERT INTO admin_notifications (type, pack_id, actor_id) VALUES ($1, $2, $3) RETURNING id, type, pack_id, actor_id, created_at, read_at
`

type CreateAdminNotificationParams struct {
	Type    string      `json:"type"`
	PackID  pgtype.UUID `json:"pack_id"`
	ActorID pgtype.UUID `json:"actor_id"`
}

// backend/db/queries/admin_notifications.sql
func (q *Queries) CreateAdminNotification(ctx context.Context, arg CreateAdminNotificationParams) (AdminNotification, error) {
	row := q.db.QueryRow(ctx, createAdminNotification, arg.Type, arg.PackID, arg.ActorID)
	var i AdminNotification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.PackID,
		&i.ActorID,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listAdminNotifications = `-- name: ListAdminNotifications :many
SELECT id, type, pack_id, actor_id, created_at, read_at FROM admin_notifications
WHERE ($1::bool = false OR read_at IS NULL)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAdminNotificationsParams struct {
	UnreadOnly bool  `json:"unread_only"`
	Off        int32 `json:"off"`
	Lim        int32 `json:"lim"`
}

func (q *Queries) ListAdminNotifications(ctx context.Context, arg ListAdminNotificationsParams) ([]AdminNotification, error) {
	rows, err := q.db.Query(ctx, listAdminNotifications, arg.UnreadOnly, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminNotification
	for rows.Next() {
		var i AdminNotification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.PackID,
			&i.ActorID,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE admin_notifications SET read_at = now() WHERE id = $1 RETURNING id, type, pack_id, actor_id, created_at, read_at
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID) (AdminNotification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, id)
	var i AdminNotification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.PackID,
		&i.ActorID,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}
