// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_types.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getGameTypeByID = `-- name: GetGameTypeByID :one
SELECT id, slug, name, description, version, supports_solo, config, created_at FROM game_types WHERE id = $1
`

func (q *Queries) GetGameTypeByID(ctx context.Context, id uuid.UUID) (GameType, error) {
	row := q.db.QueryRow(ctx, getGameTypeByID, id)
	var i GameType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.SupportsSolo,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getGameTypeBySlug = `-- name: GetGameTypeBySlug :one
SELECT id, slug, name, description, version, supports_solo, config, created_at FROM game_types WHERE slug = $1
`

func (q *Queries) GetGameTypeBySlug(ctx context.Context, slug string) (GameType, error) {
	row := q.db.QueryRow(ctx, getGameTypeBySlug, slug)
	var i GameType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.SupportsSolo,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const listGameTypes = `-- name: ListGameTypes :many

SELECT id, slug, name, description, version, supports_solo, config, created_at FROM game_types ORDER BY name
`

// backend/db/queries/game_types.sql
func (q *Queries) ListGameTypes(ctx context.Context) ([]GameType, error) {
	rows, err := q.db.Query(ctx, listGameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameType
	for rows.Next() {
		var i GameType
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.SupportsSolo,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
