// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_items.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one

INSERT INTO game_items (pack_id, name, position, payload_version)
SELECT $1, $2, COALESCE(MAX(position), 0) + 1, $3 FROM game_items WHERE pack_id = $1
RETURNING id, pack_id, position, payload_version, current_version_id, created_at, name, deleted_at, last_editor_user_id, last_edited_at
`

type CreateItemParams struct {
	PackID         uuid.UUID `json:"pack_id"`
	Name           string    `json:"name"`
	PayloadVersion int32     `json:"payload_version"`
}

// backend/db/queries/game_items.sql
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (GameItem, error) {
	row := q.db.QueryRow(ctx, createItem, arg.PackID, arg.Name, arg.PayloadVersion)
	var i GameItem
	err := row.Scan(
		&i.ID,
		&i.PackID,
		&i.Position,
		&i.PayloadVersion,
		&i.CurrentVersionID,
		&i.CreatedAt,
		&i.Name,
		&i.DeletedAt,
		&i.LastEditorUserID,
		&i.LastEditedAt,
	)
	return i, err
}

const createItemVersion = `-- name: CreateItemVersion :one
INSERT INTO game_item_versions (item_id, version_number, media_key, payload)
SELECT $1, COALESCE(MAX(version_number), 0) + 1, $2, $3 FROM game_item_versions WHERE item_id = $1
RETURNING id, item_id, version_number, media_key, payload, created_at, deleted_at
`

type CreateItemVersionParams struct {
	ItemID   uuid.UUID       `json:"item_id"`
	MediaKey *string         `json:"media_key"`
	Payload  json.RawMessage `json:"payload"`
}

func (q *Queries) CreateItemVersion(ctx context.Context, arg CreateItemVersionParams) (GameItemVersion, error) {
	row := q.db.QueryRow(ctx, createItemVersion, arg.ItemID, arg.MediaKey, arg.Payload)
	var i GameItemVersion
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.VersionNumber,
		&i.MediaKey,
		&i.Payload,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM game_items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getCurrentVersionsForItems = `-- name: GetCurrentVersionsForItems :many
SELECT gi.id AS item_id, giv.payload
FROM game_items gi
JOIN game_item_versions giv ON gi.current_version_id = giv.id
WHERE gi.id = ANY($1::uuid[])
`

type GetCurrentVersionsForItemsRow struct {
	ItemID  uuid.UUID       `json:"item_id"`
	Payload json.RawMessage `json:"payload"`
}

// Batch lookup used by the replay enrichment path for meme-showdown: given a
// set of card item IDs, return each item's current version payload so the
// handler can splice the card text into submission payloads before returning.
func (q *Queries) GetCurrentVersionsForItems(ctx context.Context, ids []uuid.UUID) ([]GetCurrentVersionsForItemsRow, error) {
	rows, err := q.db.Query(ctx, getCurrentVersionsForItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCurrentVersionsForItemsRow
	for rows.Next() {
		var i GetCurrentVersionsForItemsRow
		if err := rows.Scan(&i.ItemID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, pack_id, position, payload_version, current_version_id, created_at, name, deleted_at, last_editor_user_id, last_edited_at FROM game_items WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (GameItem, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i GameItem
	err := row.Scan(
		&i.ID,
		&i.PackID,
		&i.Position,
		&i.PayloadVersion,
		&i.CurrentVersionID,
		&i.CreatedAt,
		&i.Name,
		&i.DeletedAt,
		&i.LastEditorUserID,
		&i.LastEditedAt,
	)
	return i, err
}

const getRandomUnplayedItems = `-- name: GetRandomUnplayedItems :many
SELECT gi.id, gi.pack_id, gi.position, gi.payload_version, gi.current_version_id, gi.created_at, gi.name, gi.deleted_at, gi.last_editor_user_id, gi.last_edited_at, giv.media_key, giv.payload, giv.id AS version_id
FROM game_items gi
JOIN game_item_versions giv ON gi.current_version_id = giv.id
WHERE gi.pack_id = $1
  AND gi.payload_version = ANY($2::int[])
  AND gi.id NOT IN (
    SELECT item_id FROM rounds WHERE room_id = $3
  )
ORDER BY random()
LIMIT 1
`

type GetRandomUnplayedItemsParams struct {
	PackID   uuid.UUID `json:"pack_id"`
	Versions []int32   `json:"versions"`
	RoomID   uuid.UUID `json:"room_id"`
}

type GetRandomUnplayedItemsRow struct {
	ID               uuid.UUID          `json:"id"`
	PackID           uuid.UUID          `json:"pack_id"`
	Position         int32              `json:"position"`
	PayloadVersion   int32              `json:"payload_version"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	CreatedAt        time.Time          `json:"created_at"`
	Name             string             `json:"name"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	LastEditorUserID pgtype.UUID        `json:"last_editor_user_id"`
	LastEditedAt     pgtype.Timestamptz `json:"last_edited_at"`
	MediaKey         *string            `json:"media_key"`
	Payload          json.RawMessage    `json:"payload"`
	VersionID        uuid.UUID          `json:"version_id"`
}

func (q *Queries) GetRandomUnplayedItems(ctx context.Context, arg GetRandomUnplayedItemsParams) ([]GetRandomUnplayedItemsRow, error) {
	rows, err := q.db.Query(ctx, getRandomUnplayedItems, arg.PackID, arg.Versions, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomUnplayedItemsRow
	for rows.Next() {
		var i GetRandomUnplayedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PackID,
			&i.Position,
			&i.PayloadVersion,
			&i.CurrentVersionID,
			&i.CreatedAt,
			&i.Name,
			&i.DeletedAt,
			&i.LastEditorUserID,
			&i.LastEditedAt,
			&i.MediaKey,
			&i.Payload,
			&i.VersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVersionByID = `-- name: GetVersionByID :one
SELECT id, item_id, version_number, media_key, payload, created_at, deleted_at FROM game_item_versions WHERE id = $1
`

func (q *Queries) GetVersionByID(ctx context.Context, id uuid.UUID) (GameItemVersion, error) {
	row := q.db.QueryRow(ctx, getVersionByID, id)
	var i GameItemVersion
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.VersionNumber,
		&i.MediaKey,
		&i.Payload,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteVersion = `-- name: HardDeleteVersion :exec
DELETE FROM game_item_versions WHERE id = $1
`

func (q *Queries) HardDeleteVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteVersion, id)
	return err
}

const listItemsForPack = `-- name: ListItemsForPack :many
SELECT gi.id, gi.pack_id, gi.position, gi.payload_version, gi.current_version_id, gi.created_at, gi.name, gi.deleted_at, gi.last_editor_user_id, gi.last_edited_at, giv.media_key, giv.payload, giv.version_number
FROM game_items gi
LEFT JOIN game_item_versions giv ON gi.current_version_id = giv.id
WHERE gi.pack_id = $1 AND gi.deleted_at IS NULL
ORDER BY gi.position ASC
LIMIT $3 OFFSET $2
`

type ListItemsForPackParams struct {
	PackID uuid.UUID `json:"pack_id"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

type ListItemsForPackRow struct {
	ID               uuid.UUID          `json:"id"`
	PackID           uuid.UUID          `json:"pack_id"`
	Position         int32              `json:"position"`
	PayloadVersion   int32              `json:"payload_version"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	CreatedAt        time.Time          `json:"created_at"`
	Name             string             `json:"name"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	LastEditorUserID pgtype.UUID        `json:"last_editor_user_id"`
	LastEditedAt     pgtype.Timestamptz `json:"last_edited_at"`
	MediaKey         *string            `json:"media_key"`
	Payload          []byte             `json:"payload"`
	VersionNumber    *int32             `json:"version_number"`
}

func (q *Queries) ListItemsForPack(ctx context.Context, arg ListItemsForPackParams) ([]ListItemsForPackRow, error) {
	rows, err := q.db.Query(ctx, listItemsForPack, arg.PackID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsForPackRow
	for rows.Next() {
		var i ListItemsForPackRow
		if err := rows.Scan(
			&i.ID,
			&i.PackID,
			&i.Position,
			&i.PayloadVersion,
			&i.CurrentVersionID,
			&i.CreatedAt,
			&i.Name,
			&i.DeletedAt,
			&i.LastEditorUserID,
			&i.LastEditedAt,
			&i.MediaKey,
			&i.Payload,
			&i.VersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackItemsByPayloadVersion = `-- name: ListPackItemsByPayloadVersion :many
SELECT gi.id, giv.payload
FROM game_items gi
JOIN game_item_versions giv ON giv.id = gi.current_version_id
WHERE gi.pack_id = $1
  AND gi.deleted_at IS NULL
  AND giv.deleted_at IS NULL
  AND gi.payload_version = $2
`

type ListPackItemsByPayloadVersionParams struct {
	PackID         uuid.UUID `json:"pack_id"`
	PayloadVersion int32     `json:"payload_version"`
}

type ListPackItemsByPayloadVersionRow struct {
	ID      uuid.UUID       `json:"id"`
	Payload json.RawMessage `json:"payload"`
}

// Returns every non-deleted item in a pack whose current version payload
// matches a specific payload_version. Used by the hub to build per-game
// decks (e.g. the text-caption deck for meme-showdown) where one item per row
// is enough and a single random-pick is not.
func (q *Queries) ListPackItemsByPayloadVersion(ctx context.Context, arg ListPackItemsByPayloadVersionParams) ([]ListPackItemsByPayloadVersionRow, error) {
	rows, err := q.db.Query(ctx, listPackItemsByPayloadVersion, arg.PackID, arg.PayloadVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackItemsByPayloadVersionRow
	for rows.Next() {
		var i ListPackItemsByPayloadVersionRow
		if err := rows.Scan(&i.ID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsForItem = `-- name: ListVersionsForItem :many
SELECT id, item_id, version_number, media_key, payload, created_at, deleted_at FROM game_item_versions WHERE item_id = $1 ORDER BY version_number DESC
`

func (q *Queries) ListVersionsForItem(ctx context.Context, itemID uuid.UUID) ([]GameItemVersion, error) {
	rows, err := q.db.Query(ctx, listVersionsForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameItemVersion
	for rows.Next() {
		var i GameItemVersion
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.VersionNumber,
			&i.MediaKey,
			&i.Payload,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderItems = `-- name: ReorderItems :exec
UPDATE game_items SET position = $2 WHERE id = $1 AND pack_id = $3
`

type ReorderItemsParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
	PackID   uuid.UUID `json:"pack_id"`
}

func (q *Queries) ReorderItems(ctx context.Context, arg ReorderItemsParams) error {
	_, err := q.db.Exec(ctx, reorderItems, arg.ID, arg.Position, arg.PackID)
	return err
}

const setCurrentVersion = `-- name: SetCurrentVersion :one
UPDATE game_items SET current_version_id = $2 WHERE id = $1 RETURNING id, pack_id, position, payload_version, current_version_id, created_at, name, deleted_at, last_editor_user_id, last_edited_at
`

type SetCurrentVersionParams struct {
	ID               uuid.UUID   `json:"id"`
	CurrentVersionID pgtype.UUID `json:"current_version_id"`
}

func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) (GameItem, error) {
	row := q.db.QueryRow(ctx, setCurrentVersion, arg.ID, arg.CurrentVersionID)
	var i GameItem
	err := row.Scan(
		&i.ID,
		&i.PackID,
		&i.Position,
		&i.PayloadVersion,
		&i.CurrentVersionID,
		&i.CreatedAt,
		&i.Name,
		&i.DeletedAt,
		&i.LastEditorUserID,
		&i.LastEditedAt,
	)
	return i, err
}

const softDeleteItem = `-- name: SoftDeleteItem :exec
UPDATE game_items SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteItem, id)
	return err
}

const softDeleteVersion = `-- name: SoftDeleteVersion :exec
UPDATE game_item_versions SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteVersion, id)
	return err
}
