// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_packs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const canGuestDownloadMedia = `-- name: CanGuestDownloadMedia :one
SELECT EXISTS (
  SELECT 1
  FROM game_item_versions giv
  JOIN rounds rd ON rd.item_id = giv.item_id
  JOIN room_players rp ON rp.room_id = rd.room_id
  WHERE giv.media_key = $1
    AND giv.deleted_at IS NULL
    AND rp.guest_player_id = $2::uuid
) AS allowed
`

type CanGuestDownloadMediaParams struct {
	MediaKey      *string   `json:"media_key"`
	GuestPlayerID uuid.UUID `json:"guest_player_id"`
}

// Authorization predicate for guest reads of /api/assets/media. Guests have no
// session and cannot own packs, so the user-side rules in CanUserDownloadMedia
// don't apply. Instead we scope visibility to "items the guest could plausibly
// have seen in the room they joined" — a version is readable iff it belongs to
// an item that was actually used in a round of a room the guest is currently a
// player of. Narrower than "any media in the pack backing the room" so a guest
// can't enumerate unshown items via media_key guessing.
func (q *Queries) CanGuestDownloadMedia(ctx context.Context, arg CanGuestDownloadMediaParams) (bool, error) {
	row := q.db.QueryRow(ctx, canGuestDownloadMedia, arg.MediaKey, arg.GuestPlayerID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const canUserDownloadMedia = `-- name: CanUserDownloadMedia :one
SELECT EXISTS (
  SELECT 1
  FROM game_item_versions giv
  JOIN game_items gi ON giv.item_id = gi.id
  JOIN game_packs gp ON gi.pack_id = gp.id
  WHERE giv.media_key = $1
    AND giv.deleted_at IS NULL
    AND gp.deleted_at IS NULL
    AND (
      gp.owner_id = $2::uuid
      OR (gp.visibility = 'public' AND gp.status = 'active')
    )
) AS allowed
`

type CanUserDownloadMediaParams struct {
	MediaKey *string   `json:"media_key"`
	UserID   uuid.UUID `json:"user_id"`
}

// Authorization predicate for /api/assets/download-url. Returns true when the
// given user_id is allowed to download the media at media_key, which holds
// iff the media belongs to a non-soft-deleted version inside a non-soft-
// deleted pack that EITHER the user owns OR is public+active. Admin callers
// bypass this query entirely in the handler — encoding the role lookup in SQL
// would force a second join on users for every download.
func (q *Queries) CanUserDownloadMedia(ctx context.Context, arg CanUserDownloadMediaParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserDownloadMedia, arg.MediaKey, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const countAllPacks = `-- name: CountAllPacks :one
SELECT COUNT(*) FROM game_packs WHERE deleted_at IS NULL
`

// Total non-deleted packs, regardless of visibility or status. Used by the
// admin dashboard stats card.
func (q *Queries) CountAllPacks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllPacks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompatibleItems = `-- name: CountCompatibleItems :one
SELECT COUNT(*) FROM game_items gi
JOIN game_packs gp ON gi.pack_id = gp.id
WHERE gi.pack_id = $1
  AND gi.payload_version = ANY($2::int[])
  AND gi.deleted_at IS NULL
  AND gp.deleted_at IS NULL
`

type CountCompatibleItemsParams struct {
	PackID   uuid.UUID `json:"pack_id"`
	Versions []int32   `json:"versions"`
}

// Counts only live items in a live pack — `gi.deleted_at IS NULL` excludes
// soft-deleted items so room-creation validation can't be inflated by tombstones.
func (q *Queries) CountCompatibleItems(ctx context.Context, arg CountCompatibleItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompatibleItems, arg.PackID, arg.Versions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemsForPacks = `-- name: CountItemsForPacks :many
SELECT pack_id, COUNT(*)::bigint AS item_count
FROM game_items
WHERE pack_id = ANY($1::uuid[])
  AND deleted_at IS NULL
GROUP BY pack_id
`

type CountItemsForPacksRow struct {
	PackID    uuid.UUID `json:"pack_id"`
	ItemCount int64     `json:"item_count"`
}

// Batch row-count for the studio + host listings: returns one
// (pack_id, item_count) row per pack id requested. Soft-deleted items are
// excluded so the count matches what the user actually sees in the table.
// Packs with zero items are omitted; the API enriches missing entries to 0.
func (q *Queries) CountItemsForPacks(ctx context.Context, ids []uuid.UUID) ([]CountItemsForPacksRow, error) {
	rows, err := q.db.Query(ctx, countItemsForPacks, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountItemsForPacksRow
	for rows.Next() {
		var i CountItemsForPacksRow
		if err := rows.Scan(&i.PackID, &i.ItemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countItemsForPacksByVersion = `-- name: CountItemsForPacksByVersion :one
SELECT COALESCE(SUM(item_count), 0)::bigint AS total
FROM (
  SELECT COUNT(*)::bigint AS item_count
  FROM game_items gi
  JOIN game_packs gp ON gi.pack_id = gp.id
  WHERE gi.pack_id = ANY($1::uuid[])
    AND gi.payload_version = ANY($2::int[])
    AND gi.deleted_at IS NULL
    AND gp.deleted_at IS NULL
  GROUP BY gi.pack_id
) per_pack
`

type CountItemsForPacksByVersionParams struct {
	Ids      []uuid.UUID `json:"ids"`
	Versions []int32     `json:"versions"`
}

// Pool counter used by ValidatePackRequirements when a role lists more than
// one pack: returns the SUM of payload-version-compatible items across the
// supplied pack ids. One round-trip per role regardless of pack count.
func (q *Queries) CountItemsForPacksByVersion(ctx context.Context, arg CountItemsForPacksByVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsForPacksByVersion, arg.Ids, arg.Versions)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPack = `-- name: CreatePack :one

INSERT INTO game_packs (name, description, owner_id, is_official, visibility, language)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id
`

type CreatePackParams struct {
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	IsOfficial  bool        `json:"is_official"`
	Visibility  string      `json:"visibility"`
	Language    string      `json:"language"`
}

// backend/db/queries/game_packs.sql
func (q *Queries) CreatePack(ctx context.Context, arg CreatePackParams) (GamePack, error) {
	row := q.db.QueryRow(ctx, createPack,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.IsOfficial,
		arg.Visibility,
		arg.Language,
	)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
		&i.Language,
		&i.GroupID,
		&i.Classification,
		&i.DuplicatedFromPackID,
		&i.DuplicatedByUserID,
	)
	return i, err
}

const getPackByID = `-- name: GetPackByID :one
SELECT id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id FROM game_packs WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPackByID(ctx context.Context, id uuid.UUID) (GamePack, error) {
	row := q.db.QueryRow(ctx, getPackByID, id)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
		&i.Language,
		&i.GroupID,
		&i.Classification,
		&i.DuplicatedFromPackID,
		&i.DuplicatedByUserID,
	)
	return i, err
}

const getPackNamesByIDs = `-- name: GetPackNamesByIDs :many
SELECT id, name FROM game_packs WHERE id = ANY($1::uuid[])
`

type GetPackNamesByIDsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// Batch lookup for the audit-log enrichment path. Returns only id + name so
// the admin dashboard can resolve "pack:<uuid>" audit resources into a
// human-readable label. Soft-deleted packs are included on purpose — we
// still want audit history to show what was banned/deleted.
func (q *Queries) GetPackNamesByIDs(ctx context.Context, ids []uuid.UUID) ([]GetPackNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getPackNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPackNamesByIDsRow
	for rows.Next() {
		var i GetPackNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPacksAdmin = `-- name: ListAllPacksAdmin :many
SELECT id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id FROM game_packs
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR language = $1::text)
ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type ListAllPacksAdminParams struct {
	Language *string `json:"language"`
	Off      int32   `json:"off"`
	Lim      int32   `json:"lim"`
}

func (q *Queries) ListAllPacksAdmin(ctx context.Context, arg ListAllPacksAdminParams) ([]GamePack, error) {
	rows, err := q.db.Query(ctx, listAllPacksAdmin, arg.Language, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePack
	for rows.Next() {
		var i GamePack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.IsOfficial,
			&i.Visibility,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.IsSystem,
			&i.Language,
			&i.GroupID,
			&i.Classification,
			&i.DuplicatedFromPackID,
			&i.DuplicatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPacksForUser = `-- name: ListPacksForUser :many
SELECT id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id FROM game_packs
WHERE deleted_at IS NULL
  AND (
    owner_id = $1
    OR (visibility = 'public' AND status = 'active')
    OR group_id IN (SELECT group_id FROM group_memberships WHERE user_id = $1)
  )
  AND ($2::text IS NULL OR language = $2::text)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListPacksForUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Language *string     `json:"language"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

// Optional language filter: when sqlc.narg(language) is NULL the predicate is a no-op
// and every language is returned (preserves pre-i18n behaviour). Pass 'en' or 'fr' to
// narrow.
//
// The third WHERE branch includes packs belonging to groups the caller is a
// member of. Without it the host picker (and any other /api/packs consumer)
// stays blind to duplicated group content for non-admin members, which breaks
// the duplicate-then-host loop — admins got these rows through ListAllPacksAdmin
// but regular members had no visibility. The subquery hits
// group_memberships_user_idx, so the extra predicate is O(log n) per row.
func (q *Queries) ListPacksForUser(ctx context.Context, arg ListPacksForUserParams) ([]GamePack, error) {
	rows, err := q.db.Query(ctx, listPacksForUser,
		arg.UserID,
		arg.Language,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePack
	for rows.Next() {
		var i GamePack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.IsOfficial,
			&i.Visibility,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.IsSystem,
			&i.Language,
			&i.GroupID,
			&i.Classification,
			&i.DuplicatedFromPackID,
			&i.DuplicatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPackStatus = `-- name: SetPackStatus :one
UPDATE game_packs SET status = $2 WHERE id = $1 RETURNING id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id
`

type SetPackStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetPackStatus(ctx context.Context, arg SetPackStatusParams) (GamePack, error) {
	row := q.db.QueryRow(ctx, setPackStatus, arg.ID, arg.Status)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
		&i.Language,
		&i.GroupID,
		&i.Classification,
		&i.DuplicatedFromPackID,
		&i.DuplicatedByUserID,
	)
	return i, err
}

const softDeletePack = `-- name: SoftDeletePack :exec
UPDATE game_packs SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeletePack(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePack, id)
	return err
}

const updatePack = `-- name: UpdatePack :one
UPDATE game_packs SET name = $2, description = $3, visibility = $4, language = $5 WHERE id = $1 RETURNING id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id
`

type UpdatePackParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Visibility  string    `json:"visibility"`
	Language    string    `json:"language"`
}

func (q *Queries) UpdatePack(ctx context.Context, arg UpdatePackParams) (GamePack, error) {
	row := q.db.QueryRow(ctx, updatePack,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.Language,
	)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
		&i.Language,
		&i.GroupID,
		&i.Classification,
		&i.DuplicatedFromPackID,
		&i.DuplicatedByUserID,
	)
	return i, err
}

const upsertSystemPack = `-- name: UpsertSystemPack :one
INSERT INTO game_packs (id, name, description, owner_id, is_official, visibility, status, is_system, language)
VALUES ($1, $2, $3, NULL, true, 'public', 'active', true, $4)
ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name,
      description = EXCLUDED.description,
      is_official = true,
      visibility = 'public',
      status = 'active',
      is_system = true,
      deleted_at = NULL,
      language = EXCLUDED.language
RETURNING id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id
`

type UpsertSystemPackParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Language    string    `json:"language"`
}

// Upserts the bundled "system" pack row with a fixed sentinel UUID. Called
// once per boot from backend/internal/systempack. Forces is_official,
// visibility, status, is_system, deleted_at, and language back to their
// canonical values on every boot so the pack cannot drift from its managed
// state. The caller picks the language: image packs pass 'multi' (locale-
// agnostic content), text packs pass the authored locale.
func (q *Queries) UpsertSystemPack(ctx context.Context, arg UpsertSystemPackParams) (GamePack, error) {
	row := q.db.QueryRow(ctx, upsertSystemPack,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Language,
	)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
		&i.Language,
		&i.GroupID,
		&i.Classification,
		&i.DuplicatedFromPackID,
		&i.DuplicatedByUserID,
	)
	return i, err
}
