// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_packs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const canUserDownloadMedia = `-- name: CanUserDownloadMedia :one
SELECT EXISTS (
  SELECT 1
  FROM game_item_versions giv
  JOIN game_items gi ON giv.item_id = gi.id
  JOIN game_packs gp ON gi.pack_id = gp.id
  WHERE giv.media_key = $1
    AND giv.deleted_at IS NULL
    AND gp.deleted_at IS NULL
    AND (
      gp.owner_id = $2::uuid
      OR (gp.visibility = 'public' AND gp.status = 'active')
    )
) AS allowed
`

type CanUserDownloadMediaParams struct {
	MediaKey *string   `json:"media_key"`
	UserID   uuid.UUID `json:"user_id"`
}

// Authorization predicate for /api/assets/download-url. Returns true when the
// given user_id is allowed to download the media at media_key, which holds
// iff the media belongs to a non-soft-deleted version inside a non-soft-
// deleted pack that EITHER the user owns OR is public+active. Admin callers
// bypass this query entirely in the handler — encoding the role lookup in SQL
// would force a second join on users for every download.
func (q *Queries) CanUserDownloadMedia(ctx context.Context, arg CanUserDownloadMediaParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserDownloadMedia, arg.MediaKey, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const countAllPacks = `-- name: CountAllPacks :one
SELECT COUNT(*) FROM game_packs WHERE deleted_at IS NULL
`

// Total non-deleted packs, regardless of visibility or status. Used by the
// admin dashboard stats card.
func (q *Queries) CountAllPacks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllPacks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompatibleItems = `-- name: CountCompatibleItems :one
SELECT COUNT(*) FROM game_items gi
JOIN game_packs gp ON gi.pack_id = gp.id
WHERE gi.pack_id = $1
  AND gi.payload_version = ANY($2::int[])
  AND gp.deleted_at IS NULL
`

type CountCompatibleItemsParams struct {
	PackID   uuid.UUID `json:"pack_id"`
	Versions []int32   `json:"versions"`
}

func (q *Queries) CountCompatibleItems(ctx context.Context, arg CountCompatibleItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompatibleItems, arg.PackID, arg.Versions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPack = `-- name: CreatePack :one

INSERT INTO game_packs (name, description, owner_id, is_official, visibility)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system
`

type CreatePackParams struct {
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	IsOfficial  bool        `json:"is_official"`
	Visibility  string      `json:"visibility"`
}

// backend/db/queries/game_packs.sql
func (q *Queries) CreatePack(ctx context.Context, arg CreatePackParams) (GamePack, error) {
	row := q.db.QueryRow(ctx, createPack,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.IsOfficial,
		arg.Visibility,
	)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
	)
	return i, err
}

const getPackByID = `-- name: GetPackByID :one
SELECT id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system FROM game_packs WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPackByID(ctx context.Context, id uuid.UUID) (GamePack, error) {
	row := q.db.QueryRow(ctx, getPackByID, id)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
	)
	return i, err
}

const getPackNamesByIDs = `-- name: GetPackNamesByIDs :many
SELECT id, name FROM game_packs WHERE id = ANY($1::uuid[])
`

type GetPackNamesByIDsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// Batch lookup for the audit-log enrichment path. Returns only id + name so
// the admin dashboard can resolve "pack:<uuid>" audit resources into a
// human-readable label. Soft-deleted packs are included on purpose — we
// still want audit history to show what was banned/deleted.
func (q *Queries) GetPackNamesByIDs(ctx context.Context, ids []uuid.UUID) ([]GetPackNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getPackNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPackNamesByIDsRow
	for rows.Next() {
		var i GetPackNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPacksAdmin = `-- name: ListAllPacksAdmin :many
SELECT id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system FROM game_packs WHERE deleted_at IS NULL
ORDER BY created_at DESC LIMIT $2 OFFSET $1
`

type ListAllPacksAdminParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

func (q *Queries) ListAllPacksAdmin(ctx context.Context, arg ListAllPacksAdminParams) ([]GamePack, error) {
	rows, err := q.db.Query(ctx, listAllPacksAdmin, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePack
	for rows.Next() {
		var i GamePack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.IsOfficial,
			&i.Visibility,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPacksForUser = `-- name: ListPacksForUser :many
SELECT id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system FROM game_packs
WHERE deleted_at IS NULL
  AND (owner_id = $1 OR (visibility = 'public' AND status = 'active'))
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListPacksForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Off    int32       `json:"off"`
	Lim    int32       `json:"lim"`
}

func (q *Queries) ListPacksForUser(ctx context.Context, arg ListPacksForUserParams) ([]GamePack, error) {
	rows, err := q.db.Query(ctx, listPacksForUser, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePack
	for rows.Next() {
		var i GamePack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.IsOfficial,
			&i.Visibility,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPackStatus = `-- name: SetPackStatus :one
UPDATE game_packs SET status = $2 WHERE id = $1 RETURNING id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system
`

type SetPackStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetPackStatus(ctx context.Context, arg SetPackStatusParams) (GamePack, error) {
	row := q.db.QueryRow(ctx, setPackStatus, arg.ID, arg.Status)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
	)
	return i, err
}

const softDeletePack = `-- name: SoftDeletePack :exec
UPDATE game_packs SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeletePack(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePack, id)
	return err
}

const updatePack = `-- name: UpdatePack :one
UPDATE game_packs SET name = $2, description = $3, visibility = $4 WHERE id = $1 RETURNING id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system
`

type UpdatePackParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Visibility  string    `json:"visibility"`
}

func (q *Queries) UpdatePack(ctx context.Context, arg UpdatePackParams) (GamePack, error) {
	row := q.db.QueryRow(ctx, updatePack,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
	)
	return i, err
}

const upsertSystemPack = `-- name: UpsertSystemPack :one
INSERT INTO game_packs (id, name, description, owner_id, is_official, visibility, status, is_system)
VALUES ($1, $2, $3, NULL, true, 'public', 'active', true)
ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name,
      description = EXCLUDED.description,
      is_official = true,
      visibility = 'public',
      status = 'active',
      is_system = true,
      deleted_at = NULL
RETURNING id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system
`

type UpsertSystemPackParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

// Upserts the bundled "system" pack row with a fixed sentinel UUID. Called
// once per boot from backend/internal/systempack. Forces is_official,
// visibility, status, is_system, and deleted_at back to their canonical values
// on every boot so the pack cannot drift from its managed state.
func (q *Queries) UpsertSystemPack(ctx context.Context, arg UpsertSystemPackParams) (GamePack, error) {
	row := q.db.QueryRow(ctx, upsertSystemPack, arg.ID, arg.Name, arg.Description)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
	)
	return i, err
}
