// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_invites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeGroupInvite = `-- name: ConsumeGroupInvite :one
UPDATE group_invites SET uses_count = uses_count + 1
WHERE id = $1
  AND revoked_at IS NULL
  AND uses_count < max_uses
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id, token, group_id, created_by, kind, restricted_email, max_uses, uses_count, expires_at, revoked_at, created_at
`

// Atomic redemption check + bump. Mirrors invites.ConsumeInvite. The full set
// of preconditions (group not soft-deleted, redeemer not banned, redeemer
// under membership cap) is enforced by the handler because they need
// separate query roundtrips and per-precondition error codes.
func (q *Queries) ConsumeGroupInvite(ctx context.Context, id uuid.UUID) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, consumeGroupInvite, id)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.GroupID,
		&i.CreatedBy,
		&i.Kind,
		&i.RestrictedEmail,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveGroupInvitesForCreator = `-- name: CountActiveGroupInvitesForCreator :one
SELECT count(*) FROM group_invites
WHERE created_by = $1 AND group_id = $2
  AND revoked_at IS NULL
  AND uses_count < max_uses
  AND (expires_at IS NULL OR expires_at > now())
`

type CountActiveGroupInvitesForCreatorParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	GroupID   uuid.UUID   `json:"group_id"`
}

// Rate-limit input: how many "active" codes (unrevoked, unexpired, not yet
// exhausted) the actor currently has for the given group.
func (q *Queries) CountActiveGroupInvitesForCreator(ctx context.Context, arg CountActiveGroupInvitesForCreatorParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveGroupInvitesForCreator, arg.CreatedBy, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupInvitesMintedSince = `-- name: CountGroupInvitesMintedSince :one
SELECT count(*) FROM group_invites
WHERE created_by = $1 AND group_id = $2 AND created_at > $3
`

type CountGroupInvitesMintedSinceParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	GroupID   uuid.UUID   `json:"group_id"`
	CreatedAt time.Time   `json:"created_at"`
}

// Rate-limit input: how many codes (any state) this actor has minted in the
// given group since the cutoff. Drives the per-hour mint cap.
func (q *Queries) CountGroupInvitesMintedSince(ctx context.Context, arg CountGroupInvitesMintedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupInvitesMintedSince, arg.CreatedBy, arg.GroupID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroupInvite = `-- name: CreateGroupInvite :one

INSERT INTO group_invites (token, group_id, created_by, kind, restricted_email, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $6, $5, $7)
RETURNING id, token, group_id, created_by, kind, restricted_email, max_uses, uses_count, expires_at, revoked_at, created_at
`

type CreateGroupInviteParams struct {
	Token           string             `json:"token"`
	GroupID         uuid.UUID          `json:"group_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Kind            string             `json:"kind"`
	MaxUses         int32              `json:"max_uses"`
	RestrictedEmail *string            `json:"restricted_email"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

// backend/db/queries/group_invites.sql
func (q *Queries) CreateGroupInvite(ctx context.Context, arg CreateGroupInviteParams) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, createGroupInvite,
		arg.Token,
		arg.GroupID,
		arg.CreatedBy,
		arg.Kind,
		arg.MaxUses,
		arg.RestrictedEmail,
		arg.ExpiresAt,
	)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.GroupID,
		&i.CreatedBy,
		&i.Kind,
		&i.RestrictedEmail,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupInviteByToken = `-- name: GetGroupInviteByToken :one
SELECT id, token, group_id, created_by, kind, restricted_email, max_uses, uses_count, expires_at, revoked_at, created_at FROM group_invites WHERE token = $1
`

func (q *Queries) GetGroupInviteByToken(ctx context.Context, token string) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, getGroupInviteByToken, token)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.GroupID,
		&i.CreatedBy,
		&i.Kind,
		&i.RestrictedEmail,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupInvites = `-- name: ListGroupInvites :many
SELECT id, token, group_id, created_by, kind, restricted_email, max_uses, uses_count, expires_at, revoked_at, created_at FROM group_invites WHERE group_id = $1 ORDER BY created_at DESC
`

// Admin-facing list of every invite ever minted for the group, newest first.
// Includes consumed and revoked codes so the audit trail is visible; the UI
// filters as it likes.
func (q *Queries) ListGroupInvites(ctx context.Context, groupID uuid.UUID) ([]GroupInvite, error) {
	rows, err := q.db.Query(ctx, listGroupInvites, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupInvite
	for rows.Next() {
		var i GroupInvite
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.GroupID,
			&i.CreatedBy,
			&i.Kind,
			&i.RestrictedEmail,
			&i.MaxUses,
			&i.UsesCount,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllInvitesByCreator = `-- name: RevokeAllInvitesByCreator :exec
UPDATE group_invites
SET revoked_at = COALESCE(revoked_at, now())
WHERE created_by = $1 AND revoked_at IS NULL
`

// Used by the platform-ban cascade — every still-active code minted by the
// banned user is revoked. Idempotent.
func (q *Queries) RevokeAllInvitesByCreator(ctx context.Context, createdBy pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllInvitesByCreator, createdBy)
	return err
}

const revokeGroupInvite = `-- name: RevokeGroupInvite :one
UPDATE group_invites
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1 AND group_id = $2
RETURNING id, token, group_id, created_by, kind, restricted_email, max_uses, uses_count, expires_at, revoked_at, created_at
`

type RevokeGroupInviteParams struct {
	ID      uuid.UUID `json:"id"`
	GroupID uuid.UUID `json:"group_id"`
}

// Idempotent revoke: stamps revoked_at the first time, leaves it alone on
// subsequent calls. Returns the row so the handler can confirm the (gid,
// inviteID) pair actually matched something.
func (q *Queries) RevokeGroupInvite(ctx context.Context, arg RevokeGroupInviteParams) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, revokeGroupInvite, arg.ID, arg.GroupID)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.GroupID,
		&i.CreatedBy,
		&i.Kind,
		&i.RestrictedEmail,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
