// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_memberships.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGroupAdmins = `-- name: CountGroupAdmins :one
SELECT count(*) FROM group_memberships WHERE group_id = $1 AND role = 'admin'
`

// Used by the last-admin guard on Leave and SelfDemote.
func (q *Queries) CountGroupAdmins(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupAdmins, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*) FROM group_memberships WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupMembershipsForUser = `-- name: CountGroupMembershipsForUser :one
SELECT count(*) FROM group_memberships gm
JOIN groups g ON g.id = gm.group_id
WHERE gm.user_id = $1 AND g.deleted_at IS NULL
`

// Drives MAX_GROUP_MEMBERSHIPS_PER_USER cap on join. Counts only memberships
// in non-soft-deleted groups; a soft-deleted group still has membership rows
// but the user can't act inside it.
func (q *Queries) CountGroupMembershipsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembershipsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBan = `-- name: CreateBan :exec
INSERT INTO group_bans (group_id, user_id, banned_by)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type CreateBanParams struct {
	GroupID  uuid.UUID   `json:"group_id"`
	UserID   uuid.UUID   `json:"user_id"`
	BannedBy pgtype.UUID `json:"banned_by"`
}

// ON CONFLICT no-op so a Ban call after a previous Ban is idempotent (the
// handler may double-fire from the network layer; second call must succeed).
func (q *Queries) CreateBan(ctx context.Context, arg CreateBanParams) error {
	_, err := q.db.Exec(ctx, createBan, arg.GroupID, arg.UserID, arg.BannedBy)
	return err
}

const createMembership = `-- name: CreateMembership :one

INSERT INTO group_memberships (group_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, group_id, user_id, role, joined_at
`

type CreateMembershipParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

// backend/db/queries/group_memberships.sql
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.GroupID, arg.UserID, arg.Role)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const deleteAllMembershipsForUser = `-- name: DeleteAllMembershipsForUser :exec
DELETE FROM group_memberships WHERE user_id = $1
`

// Used by the platform-ban cascade. Drops every membership row in one shot;
// the caller is responsible for triggering auto-promotion in any group that
// this leaves admin-less.
func (q *Queries) DeleteAllMembershipsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllMembershipsForUser, userID)
	return err
}

const deleteBan = `-- name: DeleteBan :exec
DELETE FROM group_bans WHERE group_id = $1 AND user_id = $2
`

type DeleteBanParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBan(ctx context.Context, arg DeleteBanParams) error {
	_, err := q.db.Exec(ctx, deleteBan, arg.GroupID, arg.UserID)
	return err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM group_memberships WHERE group_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.GroupID, arg.UserID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, group_id, user_id, role, joined_at FROM group_memberships WHERE group_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.GroupID, arg.UserID)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const isUserBannedFromGroup = `-- name: IsUserBannedFromGroup :one
SELECT EXISTS(SELECT 1 FROM group_bans WHERE group_id = $1 AND user_id = $2) AS banned
`

type IsUserBannedFromGroupParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) IsUserBannedFromGroup(ctx context.Context, arg IsUserBannedFromGroupParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBannedFromGroup, arg.GroupID, arg.UserID)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const listGroupBans = `-- name: ListGroupBans :many
SELECT gb.id, gb.group_id, gb.user_id, gb.banned_by, gb.banned_at, u.username
FROM group_bans gb
JOIN users u ON u.id = gb.user_id
WHERE gb.group_id = $1
ORDER BY gb.banned_at DESC
`

type ListGroupBansRow struct {
	ID       uuid.UUID   `json:"id"`
	GroupID  uuid.UUID   `json:"group_id"`
	UserID   uuid.UUID   `json:"user_id"`
	BannedBy pgtype.UUID `json:"banned_by"`
	BannedAt time.Time   `json:"banned_at"`
	Username string      `json:"username"`
}

func (q *Queries) ListGroupBans(ctx context.Context, groupID uuid.UUID) ([]ListGroupBansRow, error) {
	rows, err := q.db.Query(ctx, listGroupBans, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupBansRow
	for rows.Next() {
		var i ListGroupBansRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.BannedBy,
			&i.BannedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.id, gm.group_id, gm.user_id, gm.role, gm.joined_at, u.username, u.last_login_at
FROM group_memberships gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY (gm.role = 'admin') DESC, gm.joined_at ASC
`

type ListGroupMembersRow struct {
	ID          uuid.UUID          `json:"id"`
	GroupID     uuid.UUID          `json:"group_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    time.Time          `json:"joined_at"`
	Username    string             `json:"username"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

// Admins always sort first so the UI doesn't need a second pass to surface
// moderators. last_login_at is exposed so phase-2 auto-promotion / dormancy
// views can render without a second join.
func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsWhereUserIsSoleAdmin = `-- name: ListGroupsWhereUserIsSoleAdmin :many
SELECT gm.group_id
FROM group_memberships gm
WHERE gm.user_id = $1 AND gm.role = 'admin'
  AND NOT EXISTS (
    SELECT 1 FROM group_memberships gm2
    WHERE gm2.group_id = gm.group_id
      AND gm2.role = 'admin'
      AND gm2.user_id != gm.user_id
  )
`

// Used by the platform-ban cascade BEFORE deleting memberships, so the
// caller knows which groups need an immediate auto-promotion run.
func (q *Queries) ListGroupsWhereUserIsSoleAdmin(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listGroupsWhereUserIsSoleAdmin, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var group_id uuid.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickPromotionCandidate = `-- name: PickPromotionCandidate :one
SELECT gm.user_id
FROM group_memberships gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
  AND gm.role = 'member'
  AND u.last_login_at IS NOT NULL
  AND u.last_login_at >= now() - $2::interval
ORDER BY gm.joined_at ASC
LIMIT 1
`

type PickPromotionCandidateParams struct {
	GroupID      uuid.UUID       `json:"group_id"`
	DormantAfter pgtype.Interval `json:"dormant_after"`
}

// Finds the longest-tenured "active" (logged in within the dormancy window)
// non-admin member of a group. Returns no rows when no candidate exists; the
// caller surfaces that as a platform-admin notification per the spec.
func (q *Queries) PickPromotionCandidate(ctx context.Context, arg PickPromotionCandidateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, pickPromotionCandidate, arg.GroupID, arg.DormantAfter)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const scanDormantSoleAdmins = `-- name: ScanDormantSoleAdmins :many
SELECT gm.group_id, gm.user_id
FROM group_memberships gm
JOIN users u ON u.id = gm.user_id
JOIN groups g ON g.id = gm.group_id
WHERE g.deleted_at IS NULL
  AND gm.role = 'admin'
  AND (u.last_login_at IS NULL OR u.last_login_at < now() - $1::interval)
  AND NOT EXISTS (
    SELECT 1 FROM group_memberships gm2
    JOIN users u2 ON u2.id = gm2.user_id
    WHERE gm2.group_id = gm.group_id
      AND gm2.role = 'admin'
      AND gm2.user_id != gm.user_id
      AND u2.last_login_at IS NOT NULL
      AND u2.last_login_at >= now() - $1::interval
  )
`

type ScanDormantSoleAdminsRow struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// The 90-day auto-promotion scan. Returns each (group_id, dormant_admin_id)
// pair where the admin has not logged in for 90+ days AND no other admin in
// the group has logged in within that window. The caller iterates and either
// promotes the longest-tenured active member or notifies the platform admin.
func (q *Queries) ScanDormantSoleAdmins(ctx context.Context, dormantAfter pgtype.Interval) ([]ScanDormantSoleAdminsRow, error) {
	rows, err := q.db.Query(ctx, scanDormantSoleAdmins, dormantAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanDormantSoleAdminsRow
	for rows.Next() {
		var i ScanDormantSoleAdminsRow
		if err := rows.Scan(&i.GroupID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE group_memberships
SET role = $3
WHERE group_id = $1 AND user_id = $2
RETURNING id, group_id, user_id, role, joined_at
`

type UpdateMembershipRoleParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.GroupID, arg.UserID, arg.Role)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
