// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_notifications.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadGroupNotifications = `-- name: CountUnreadGroupNotifications :one
SELECT count(*) FROM group_notifications WHERE group_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadGroupNotifications(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadGroupNotifications, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroupNotification = `-- name: CreateGroupNotification :one

INSERT INTO group_notifications (group_id, type, actor_id, subject_id, payload)
VALUES ($1, $2, $4, $5, $3)
RETURNING id, group_id, type, actor_id, subject_id, payload, created_at, read_at
`

type CreateGroupNotificationParams struct {
	GroupID   uuid.UUID       `json:"group_id"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
	ActorID   pgtype.UUID     `json:"actor_id"`
	SubjectID pgtype.UUID     `json:"subject_id"`
}

// backend/db/queries/group_notifications.sql
// Per-group notification stream. Parallel to admin_notifications but scoped
// to a group so the feed isn't polluted by cross-group moderation traffic.
func (q *Queries) CreateGroupNotification(ctx context.Context, arg CreateGroupNotificationParams) (GroupNotification, error) {
	row := q.db.QueryRow(ctx, createGroupNotification,
		arg.GroupID,
		arg.Type,
		arg.Payload,
		arg.ActorID,
		arg.SubjectID,
	)
	var i GroupNotification
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Type,
		&i.ActorID,
		&i.SubjectID,
		&i.Payload,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listGroupNotifications = `-- name: ListGroupNotifications :many
SELECT id, group_id, type, actor_id, subject_id, payload, created_at, read_at FROM group_notifications
WHERE group_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListGroupNotificationsParams struct {
	GroupID uuid.UUID `json:"group_id"`
	Off     int32     `json:"off"`
	Lim     int32     `json:"lim"`
}

// Paginated descending-by-time list for the group's admins. The handler
// gates access on admin role before calling.
func (q *Queries) ListGroupNotifications(ctx context.Context, arg ListGroupNotificationsParams) ([]GroupNotification, error) {
	rows, err := q.db.Query(ctx, listGroupNotifications, arg.GroupID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupNotification
	for rows.Next() {
		var i GroupNotification
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Type,
			&i.ActorID,
			&i.SubjectID,
			&i.Payload,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGroupNotificationRead = `-- name: MarkGroupNotificationRead :exec
UPDATE group_notifications SET read_at = now()
WHERE id = $1 AND group_id = $2 AND read_at IS NULL
`

type MarkGroupNotificationReadParams struct {
	ID      uuid.UUID `json:"id"`
	GroupID uuid.UUID `json:"group_id"`
}

func (q *Queries) MarkGroupNotificationRead(ctx context.Context, arg MarkGroupNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markGroupNotificationRead, arg.ID, arg.GroupID)
	return err
}
