// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_duplication.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingDuplication = `-- name: CreatePendingDuplication :one

INSERT INTO group_duplication_pending (group_id, source_pack_id, requested_by)
VALUES ($1, $2, $3)
RETURNING id, group_id, source_pack_id, requested_by, requested_at, resolved_at, resolved_by, resolution
`

type CreatePendingDuplicationParams struct {
	GroupID      uuid.UUID `json:"group_id"`
	SourcePackID uuid.UUID `json:"source_pack_id"`
	RequestedBy  uuid.UUID `json:"requested_by"`
}

// backend/db/queries/group_duplication.sql
// NSFW→SFW approval queue. See docs/superpowers/specs/2026-04-22-groups-paradigm-design.md.
func (q *Queries) CreatePendingDuplication(ctx context.Context, arg CreatePendingDuplicationParams) (GroupDuplicationPending, error) {
	row := q.db.QueryRow(ctx, createPendingDuplication, arg.GroupID, arg.SourcePackID, arg.RequestedBy)
	var i GroupDuplicationPending
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SourcePackID,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
	)
	return i, err
}

const getPendingDuplication = `-- name: GetPendingDuplication :one
SELECT id, group_id, source_pack_id, requested_by, requested_at, resolved_at, resolved_by, resolution FROM group_duplication_pending WHERE id = $1
`

func (q *Queries) GetPendingDuplication(ctx context.Context, id uuid.UUID) (GroupDuplicationPending, error) {
	row := q.db.QueryRow(ctx, getPendingDuplication, id)
	var i GroupDuplicationPending
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SourcePackID,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
	)
	return i, err
}

const listOpenPendingDuplications = `-- name: ListOpenPendingDuplications :many
SELECT gdp.id, gdp.group_id, gdp.source_pack_id, gdp.requested_by, gdp.requested_at, gdp.resolved_at, gdp.resolved_by, gdp.resolution, gp.name AS source_pack_name, gp.classification AS source_classification,
       u.username AS requested_by_username
FROM group_duplication_pending gdp
JOIN game_packs gp ON gp.id = gdp.source_pack_id
JOIN users u ON u.id = gdp.requested_by
WHERE gdp.group_id = $1 AND gdp.resolved_at IS NULL
ORDER BY gdp.requested_at DESC
`

type ListOpenPendingDuplicationsRow struct {
	ID                   uuid.UUID          `json:"id"`
	GroupID              uuid.UUID          `json:"group_id"`
	SourcePackID         uuid.UUID          `json:"source_pack_id"`
	RequestedBy          uuid.UUID          `json:"requested_by"`
	RequestedAt          time.Time          `json:"requested_at"`
	ResolvedAt           pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy           pgtype.UUID        `json:"resolved_by"`
	Resolution           *string            `json:"resolution"`
	SourcePackName       string             `json:"source_pack_name"`
	SourceClassification string             `json:"source_classification"`
	RequestedByUsername  string             `json:"requested_by_username"`
}

// Admin-facing queue view for a group. Excludes resolved rows by design so
// the list stays focused on what needs action.
func (q *Queries) ListOpenPendingDuplications(ctx context.Context, groupID uuid.UUID) ([]ListOpenPendingDuplicationsRow, error) {
	rows, err := q.db.Query(ctx, listOpenPendingDuplications, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenPendingDuplicationsRow
	for rows.Next() {
		var i ListOpenPendingDuplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SourcePackID,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.Resolution,
			&i.SourcePackName,
			&i.SourceClassification,
			&i.RequestedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePendingDuplication = `-- name: ResolvePendingDuplication :one
UPDATE group_duplication_pending
SET resolved_at = now(), resolved_by = $2, resolution = $3
WHERE id = $1 AND resolved_at IS NULL
RETURNING id, group_id, source_pack_id, requested_by, requested_at, resolved_at, resolved_by, resolution
`

type ResolvePendingDuplicationParams struct {
	ID         uuid.UUID   `json:"id"`
	ResolvedBy pgtype.UUID `json:"resolved_by"`
	Resolution *string     `json:"resolution"`
}

// Single-shot resolve: stamps resolved_at/resolved_by/resolution, returns the
// updated row. Idempotent on resolution — a second accept/reject is rejected
// by the handler via the resolved_at check, not here.
func (q *Queries) ResolvePendingDuplication(ctx context.Context, arg ResolvePendingDuplicationParams) (GroupDuplicationPending, error) {
	row := q.db.QueryRow(ctx, resolvePendingDuplication, arg.ID, arg.ResolvedBy, arg.Resolution)
	var i GroupDuplicationPending
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SourcePackID,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
	)
	return i, err
}
