// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCreatedGroupsForUser = `-- name: CountCreatedGroupsForUser :one
SELECT count(*) FROM groups
WHERE created_by = $1 AND deleted_at IS NULL
`

// How many live groups the given user originally created. Used by the
// per-user create cap (MAX_GROUPS_PER_USER).
func (q *Queries) CountCreatedGroupsForUser(ctx context.Context, createdBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCreatedGroupsForUser, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupsForUser = `-- name: CountGroupsForUser :one
SELECT count(*) FROM group_memberships gm
JOIN groups g ON g.id = gm.group_id
WHERE gm.user_id = $1 AND g.deleted_at IS NULL
`

// How many live groups the given user is currently a member of (any role).
func (q *Queries) CountGroupsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (name, description, language, classification, quota_bytes, created_by, avatar_media_key, member_cap)
VALUES ($1, $2, $3, $4, $5, $6, $8, $7)
RETURNING id, name, name_normalized, description, avatar_media_key, language, classification, member_cap, quota_bytes, created_by, created_at, deleted_at
`

type CreateGroupParams struct {
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	Language       string      `json:"language"`
	Classification string      `json:"classification"`
	QuotaBytes     int64       `json:"quota_bytes"`
	CreatedBy      pgtype.UUID `json:"created_by"`
	MemberCap      int32       `json:"member_cap"`
	AvatarMediaKey *string     `json:"avatar_media_key"`
}

// backend/db/queries/groups.sql
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.Language,
		arg.Classification,
		arg.QuotaBytes,
		arg.CreatedBy,
		arg.MemberCap,
		arg.AvatarMediaKey,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.AvatarMediaKey,
		&i.Language,
		&i.Classification,
		&i.MemberCap,
		&i.QuotaBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, name_normalized, description, avatar_media_key, language, classification, member_cap, quota_bytes, created_by, created_at, deleted_at FROM groups WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.AvatarMediaKey,
		&i.Language,
		&i.Classification,
		&i.MemberCap,
		&i.QuotaBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGroupByIDIncludingDeleted = `-- name: GetGroupByIDIncludingDeleted :one
SELECT id, name, name_normalized, description, avatar_media_key, language, classification, member_cap, quota_bytes, created_by, created_at, deleted_at FROM groups WHERE id = $1
`

// Used by the soft-delete restore flow; returns the row even when deleted_at
// is set so the handler can decide whether the 30-day window has elapsed.
func (q *Queries) GetGroupByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByIDIncludingDeleted, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.AvatarMediaKey,
		&i.Language,
		&i.Classification,
		&i.MemberCap,
		&i.QuotaBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGroupByNormalizedName = `-- name: GetGroupByNormalizedName :one
SELECT id, name, name_normalized, description, avatar_media_key, language, classification, member_cap, quota_bytes, created_by, created_at, deleted_at FROM groups WHERE name_normalized = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGroupByNormalizedName(ctx context.Context, nameNormalized *string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByNormalizedName, nameNormalized)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.AvatarMediaKey,
		&i.Language,
		&i.Classification,
		&i.MemberCap,
		&i.QuotaBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllGroupsAdmin = `-- name: ListAllGroupsAdmin :many
SELECT g.id, g.name, g.name_normalized, g.description, g.avatar_media_key, g.language, g.classification, g.member_cap, g.quota_bytes, g.created_by, g.created_at, g.deleted_at, (SELECT count(*) FROM group_memberships gm WHERE gm.group_id = g.id)::bigint AS member_count
FROM groups g
ORDER BY g.created_at DESC
LIMIT $2 OFFSET $1
`

type ListAllGroupsAdminParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type ListAllGroupsAdminRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	NameNormalized *string            `json:"name_normalized"`
	Description    string             `json:"description"`
	AvatarMediaKey *string            `json:"avatar_media_key"`
	Language       string             `json:"language"`
	Classification string             `json:"classification"`
	MemberCap      int32              `json:"member_cap"`
	QuotaBytes     int64              `json:"quota_bytes"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	MemberCount    int64              `json:"member_count"`
}

// Platform admin view: every live and soft-deleted group with a current
// member count. Pagination via lim/off.
func (q *Queries) ListAllGroupsAdmin(ctx context.Context, arg ListAllGroupsAdminParams) ([]ListAllGroupsAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllGroupsAdmin, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGroupsAdminRow
	for rows.Next() {
		var i ListAllGroupsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Description,
			&i.AvatarMediaKey,
			&i.Language,
			&i.Classification,
			&i.MemberCap,
			&i.QuotaBytes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.name, g.name_normalized, g.description, g.avatar_media_key, g.language, g.classification, g.member_cap, g.quota_bytes, g.created_by, g.created_at, g.deleted_at, gm.role AS member_role
FROM groups g
JOIN group_memberships gm ON gm.group_id = g.id
WHERE gm.user_id = $1 AND g.deleted_at IS NULL
ORDER BY g.created_at DESC
`

type ListGroupsForUserRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	NameNormalized *string            `json:"name_normalized"`
	Description    string             `json:"description"`
	AvatarMediaKey *string            `json:"avatar_media_key"`
	Language       string             `json:"language"`
	Classification string             `json:"classification"`
	MemberCap      int32              `json:"member_cap"`
	QuotaBytes     int64              `json:"quota_bytes"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	MemberRole     string             `json:"member_role"`
}

func (q *Queries) ListGroupsForUser(ctx context.Context, userID uuid.UUID) ([]ListGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsForUserRow
	for rows.Next() {
		var i ListGroupsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Description,
			&i.AvatarMediaKey,
			&i.Language,
			&i.Classification,
			&i.MemberCap,
			&i.QuotaBytes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreGroup = `-- name: RestoreGroup :exec
UPDATE groups SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL AND deleted_at > now() - interval '30 days'
`

// Clears deleted_at if the soft-delete is still inside the 30-day window.
// A row outside the window is left untouched; the handler verifies via a
// subsequent GetGroupByID and surfaces 410 Gone when restore was a no-op.
func (q *Queries) RestoreGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreGroup, id)
	return err
}

const setGroupMemberCap = `-- name: SetGroupMemberCap :exec
UPDATE groups SET member_cap = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetGroupMemberCapParams struct {
	ID        uuid.UUID `json:"id"`
	MemberCap int32     `json:"member_cap"`
}

// Platform-admin override of the per-group member cap.
func (q *Queries) SetGroupMemberCap(ctx context.Context, arg SetGroupMemberCapParams) error {
	_, err := q.db.Exec(ctx, setGroupMemberCap, arg.ID, arg.MemberCap)
	return err
}

const setGroupQuotaBytes = `-- name: SetGroupQuotaBytes :exec
UPDATE groups SET quota_bytes = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetGroupQuotaBytesParams struct {
	ID         uuid.UUID `json:"id"`
	QuotaBytes int64     `json:"quota_bytes"`
}

// Platform-admin override of the per-group asset cap. Members and group
// admins see the current value but cannot mutate it.
func (q *Queries) SetGroupQuotaBytes(ctx context.Context, arg SetGroupQuotaBytesParams) error {
	_, err := q.db.Exec(ctx, setGroupQuotaBytes, arg.ID, arg.QuotaBytes)
	return err
}

const softDeleteGroup = `-- name: SoftDeleteGroup :exec
UPDATE groups SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteGroup, id)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name             = COALESCE($2, name),
    description      = COALESCE($3, description),
    language         = COALESCE($4, language),
    classification   = COALESCE($5, classification),
    avatar_media_key = CASE WHEN $6::boolean THEN $7 ELSE avatar_media_key END
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, name_normalized, description, avatar_media_key, language, classification, member_cap, quota_bytes, created_by, created_at, deleted_at
`

type UpdateGroupParams struct {
	ID             uuid.UUID `json:"id"`
	Name           *string   `json:"name"`
	Description    *string   `json:"description"`
	Language       *string   `json:"language"`
	Classification *string   `json:"classification"`
	AvatarSet      bool      `json:"avatar_set"`
	AvatarMediaKey *string   `json:"avatar_media_key"`
}

// COALESCE-with-narg lets the handler pass nil for fields the caller did not
// send. The avatar column is special: a nil narg means "don't touch", but the
// caller sometimes wants to clear the avatar — represented by avatar_set=true
// with a NULL avatar_media_key.
func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Language,
		arg.Classification,
		arg.AvatarSet,
		arg.AvatarMediaKey,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.AvatarMediaKey,
		&i.Language,
		&i.Classification,
		&i.MemberCap,
		&i.QuotaBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
