// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_packs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpGroupItemEditor = `-- name: BumpGroupItemEditor :exec
UPDATE game_items
SET last_editor_user_id = $2, last_edited_at = now()
WHERE id = $1
`

type BumpGroupItemEditorParams struct {
	ID               uuid.UUID   `json:"id"`
	LastEditorUserID pgtype.UUID `json:"last_editor_user_id"`
}

// Stamps the (last_editor_user_id, last_edited_at) audit pair on a group-pack
// item after a successful add or modify. A no-op on non-group items (the
// handler only calls it when it just loaded a group pack).
func (q *Queries) BumpGroupItemEditor(ctx context.Context, arg BumpGroupItemEditorParams) error {
	_, err := q.db.Exec(ctx, bumpGroupItemEditor, arg.ID, arg.LastEditorUserID)
	return err
}

const createGroupPack = `-- name: CreateGroupPack :one

INSERT INTO game_packs (
    name, description, owner_id, is_official, visibility, language,
    group_id, classification, duplicated_from_pack_id, duplicated_by_user_id
)
VALUES (
    $1, $5, NULL, false, 'private', $2,
    $3, $4, $6, $7
)
RETURNING id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id
`

type CreateGroupPackParams struct {
	Name                 string      `json:"name"`
	Language             string      `json:"language"`
	GroupID              pgtype.UUID `json:"group_id"`
	Classification       string      `json:"classification"`
	Description          *string     `json:"description"`
	DuplicatedFromPackID pgtype.UUID `json:"duplicated_from_pack_id"`
	DuplicatedByUserID   pgtype.UUID `json:"duplicated_by_user_id"`
}

// backend/db/queries/group_packs.sql
// Phase 3 of the groups paradigm. The existing game_packs queries cover
// user-owned and system packs; this file adds the group-owned shape.
// Internal helper used by the duplication service; handler-level flows never
// call it directly. owner_id stays NULL and is_official stays false — the
// group_packs_group_no_user_owner_chk + group_packs_group_not_system_chk
// constraints enforce that invariant.
func (q *Queries) CreateGroupPack(ctx context.Context, arg CreateGroupPackParams) (GamePack, error) {
	row := q.db.QueryRow(ctx, createGroupPack,
		arg.Name,
		arg.Language,
		arg.GroupID,
		arg.Classification,
		arg.Description,
		arg.DuplicatedFromPackID,
		arg.DuplicatedByUserID,
	)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
		&i.Language,
		&i.GroupID,
		&i.Classification,
		&i.DuplicatedFromPackID,
		&i.DuplicatedByUserID,
	)
	return i, err
}

const forceGroupClassificationNSFW = `-- name: ForceGroupClassificationNSFW :exec
UPDATE groups SET classification = 'nsfw'
WHERE id = $1 AND deleted_at IS NULL
`

// Used by the duplication approval flow when an admin accepts an NSFW pack
// into a SFW group — per spec the group is force-relabeled NSFW.
func (q *Queries) ForceGroupClassificationNSFW(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, forceGroupClassificationNSFW, id)
	return err
}

const getGroupPack = `-- name: GetGroupPack :one
SELECT id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id FROM game_packs WHERE id = $1 AND deleted_at IS NULL
`

// Member-gated read path used by the pack detail page. Does not short-circuit
// on group ownership — the handler verifies the pack.group_id matches the
// URL gid so we never serve a cross-group pack by accident.
func (q *Queries) GetGroupPack(ctx context.Context, id uuid.UUID) (GamePack, error) {
	row := q.db.QueryRow(ctx, getGroupPack, id)
	var i GamePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.IsOfficial,
		&i.Visibility,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsSystem,
		&i.Language,
		&i.GroupID,
		&i.Classification,
		&i.DuplicatedFromPackID,
		&i.DuplicatedByUserID,
	)
	return i, err
}

const listGroupPacks = `-- name: ListGroupPacks :many
SELECT id, name, description, owner_id, is_official, visibility, status, created_at, deleted_at, is_system, language, group_id, classification, duplicated_from_pack_id, duplicated_by_user_id FROM game_packs
WHERE group_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

// Every non-soft-deleted pack belonging to the group, newest first. The UI
// filters by status client-side; `flagged` and `banned` packs are still
// visible to the group so admins can see what the platform moderated.
func (q *Queries) ListGroupPacks(ctx context.Context, groupID pgtype.UUID) ([]GamePack, error) {
	rows, err := q.db.Query(ctx, listGroupPacks, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePack
	for rows.Next() {
		var i GamePack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.IsOfficial,
			&i.Visibility,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.IsSystem,
			&i.Language,
			&i.GroupID,
			&i.Classification,
			&i.DuplicatedFromPackID,
			&i.DuplicatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGroupPack = `-- name: SoftDeleteGroupPack :exec
UPDATE game_packs SET deleted_at = now()
WHERE id = $1 AND group_id = $2 AND deleted_at IS NULL
`

type SoftDeleteGroupPackParams struct {
	ID      uuid.UUID   `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

// Admin-only eviction. Uses the existing deleted_at column so historical
// rooms that referenced the pack keep functioning via replay-redaction.
func (q *Queries) SoftDeleteGroupPack(ctx context.Context, arg SoftDeleteGroupPackParams) error {
	_, err := q.db.Exec(ctx, softDeleteGroupPack, arg.ID, arg.GroupID)
	return err
}

const sumGroupPackMediaSize = `-- name: SumGroupPackMediaSize :one
SELECT COUNT(*)::bigint FROM game_item_versions giv
JOIN game_items gi ON gi.id = giv.item_id
JOIN game_packs gp ON gp.id = gi.pack_id
WHERE gp.group_id = $1
  AND gp.deleted_at IS NULL
  AND gi.deleted_at IS NULL
  AND giv.deleted_at IS NULL
  AND giv.media_key IS NOT NULL
`

// Approximate quota fill: we don't have stored byte sizes per media object in
// phase 3 so this returns the COUNT of current versions that carry a
// media_key. The duplication service multiplies by an estimated average
// size (`groupMediaSizeEstimateBytes`) for the pre-flight check — quota is
// a soft bound for now and will be tightened once storage metadata lands.
func (q *Queries) SumGroupPackMediaSize(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumGroupPackMediaSize, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
