// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guest_players.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createGuestPlayer = `-- name: CreateGuestPlayer :one

INSERT INTO guest_players (room_id, display_name, token_hash)
VALUES ($1, $2, $3)
RETURNING id, room_id, display_name, token_hash, created_at, last_seen_at
`

type CreateGuestPlayerParams struct {
	RoomID      uuid.UUID `json:"room_id"`
	DisplayName string    `json:"display_name"`
	TokenHash   string    `json:"token_hash"`
}

// backend/db/queries/guest_players.sql
func (q *Queries) CreateGuestPlayer(ctx context.Context, arg CreateGuestPlayerParams) (GuestPlayer, error) {
	row := q.db.QueryRow(ctx, createGuestPlayer, arg.RoomID, arg.DisplayName, arg.TokenHash)
	var i GuestPlayer
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.DisplayName,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteGuestPlayersForRoom = `-- name: DeleteGuestPlayersForRoom :exec
DELETE FROM guest_players WHERE room_id = $1
`

func (q *Queries) DeleteGuestPlayersForRoom(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGuestPlayersForRoom, roomID)
	return err
}

const getGuestPlayerByID = `-- name: GetGuestPlayerByID :one
SELECT id, room_id, display_name, token_hash, created_at, last_seen_at FROM guest_players WHERE id = $1
`

func (q *Queries) GetGuestPlayerByID(ctx context.Context, id uuid.UUID) (GuestPlayer, error) {
	row := q.db.QueryRow(ctx, getGuestPlayerByID, id)
	var i GuestPlayer
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.DisplayName,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getGuestPlayerByTokenHash = `-- name: GetGuestPlayerByTokenHash :one
SELECT id, room_id, display_name, token_hash, created_at, last_seen_at FROM guest_players WHERE token_hash = $1
`

func (q *Queries) GetGuestPlayerByTokenHash(ctx context.Context, tokenHash string) (GuestPlayer, error) {
	row := q.db.QueryRow(ctx, getGuestPlayerByTokenHash, tokenHash)
	var i GuestPlayer
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.DisplayName,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchGuestPlayer = `-- name: TouchGuestPlayer :exec
UPDATE guest_players SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchGuestPlayer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchGuestPlayer, id)
	return err
}
