// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites SET uses_count = uses_count + 1
WHERE id = $1
  AND (max_uses = 0 OR uses_count < max_uses)
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id, token, created_by, label, restricted_email, max_uses, uses_count, expires_at, created_at
`

func (q *Queries) ConsumeInvite(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, consumeInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedBy,
		&i.Label,
		&i.RestrictedEmail,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countInvites = `-- name: CountInvites :one
SELECT COUNT(*) FROM invites
`

func (q *Queries) CountInvites(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO invites (token, created_by, label, restricted_email, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, token, created_by, label, restricted_email, max_uses, uses_count, expires_at, created_at
`

type CreateInviteParams struct {
	Token           string             `json:"token"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Label           *string            `json:"label"`
	RestrictedEmail *string            `json:"restricted_email"`
	MaxUses         int32              `json:"max_uses"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

// backend/db/queries/invites.sql
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.Token,
		arg.CreatedBy,
		arg.Label,
		arg.RestrictedEmail,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedBy,
		&i.Label,
		&i.RestrictedEmail,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, token, created_by, label, restricted_email, max_uses, uses_count, expires_at, created_at FROM invites WHERE token = $1
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedBy,
		&i.Label,
		&i.RestrictedEmail,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, token, created_by, label, restricted_email, max_uses, uses_count, expires_at, created_at FROM invites ORDER BY created_at DESC LIMIT $2 OFFSET $1
`

type ListInvitesParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.CreatedBy,
			&i.Label,
			&i.RestrictedEmail,
			&i.MaxUses,
			&i.UsesCount,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
