// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: magic_link_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeMagicLinkToken = `-- name: ConsumeMagicLinkToken :one
UPDATE magic_link_tokens SET used_at = now() WHERE id = $1 RETURNING id, user_id, token_hash, purpose, expires_at, used_at, created_at
`

func (q *Queries) ConsumeMagicLinkToken(ctx context.Context, id uuid.UUID) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, consumeMagicLinkToken, id)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMagicLinkToken = `-- name: CreateMagicLinkToken :one

INSERT INTO magic_link_tokens (user_id, token_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, purpose, expires_at, used_at, created_at
`

type CreateMagicLinkTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

// backend/db/queries/magic_link_tokens.sql
func (q *Queries) CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, createMagicLinkToken,
		arg.UserID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredUnusedTokens = `-- name: DeleteExpiredUnusedTokens :exec
DELETE FROM magic_link_tokens WHERE expires_at < now() AND used_at IS NULL
`

func (q *Queries) DeleteExpiredUnusedTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredUnusedTokens)
	return err
}

const deleteOldUsedTokens = `-- name: DeleteOldUsedTokens :exec
DELETE FROM magic_link_tokens
WHERE used_at IS NOT NULL AND used_at < now() - interval '7 days'
`

func (q *Queries) DeleteOldUsedTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldUsedTokens)
	return err
}

const getMagicLinkToken = `-- name: GetMagicLinkToken :one
SELECT id, user_id, token_hash, purpose, expires_at, used_at, created_at FROM magic_link_tokens
WHERE token_hash = $1 AND expires_at > now() AND used_at IS NULL
`

func (q *Queries) GetMagicLinkToken(ctx context.Context, tokenHash string) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, getMagicLinkToken, tokenHash)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeMagicLinkTokenAtomic = `-- name: ConsumeMagicLinkTokenAtomic :one
UPDATE magic_link_tokens
SET used_at = NOW()
WHERE token_hash = $1
  AND expires_at > NOW()
  AND used_at IS NULL
RETURNING id, user_id, token_hash, purpose, expires_at, used_at, created_at
`

func (q *Queries) ConsumeMagicLinkTokenAtomic(ctx context.Context, tokenHash string) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, consumeMagicLinkTokenAtomic, tokenHash)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidatePendingTokens = `-- name: InvalidatePendingTokens :exec
UPDATE magic_link_tokens SET used_at = now()
WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
`

type InvalidatePendingTokensParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Purpose string    `json:"purpose"`
}

func (q *Queries) InvalidatePendingTokens(ctx context.Context, arg InvalidatePendingTokensParams) error {
	_, err := q.db.Exec(ctx, invalidatePendingTokens, arg.UserID, arg.Purpose)
	return err
}
