// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminNotification struct {
	ID        uuid.UUID          `json:"id"`
	Type      string             `json:"type"`
	PackID    pgtype.UUID        `json:"pack_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	CreatedAt time.Time          `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type AuditLog struct {
	ID        uuid.UUID       `json:"id"`
	AdminID   pgtype.UUID     `json:"admin_id"`
	Action    string          `json:"action"`
	Resource  string          `json:"resource"`
	Changes   json.RawMessage `json:"changes"`
	CreatedAt time.Time       `json:"created_at"`
}

type GameItem struct {
	ID               uuid.UUID          `json:"id"`
	PackID           uuid.UUID          `json:"pack_id"`
	Position         int32              `json:"position"`
	PayloadVersion   int32              `json:"payload_version"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	CreatedAt        time.Time          `json:"created_at"`
	Name             string             `json:"name"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	LastEditorUserID pgtype.UUID        `json:"last_editor_user_id"`
	LastEditedAt     pgtype.Timestamptz `json:"last_edited_at"`
}

type GameItemVersion struct {
	ID            uuid.UUID          `json:"id"`
	ItemID        uuid.UUID          `json:"item_id"`
	VersionNumber int32              `json:"version_number"`
	MediaKey      *string            `json:"media_key"`
	Payload       json.RawMessage    `json:"payload"`
	CreatedAt     time.Time          `json:"created_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type GamePack struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Description          *string            `json:"description"`
	OwnerID              pgtype.UUID        `json:"owner_id"`
	IsOfficial           bool               `json:"is_official"`
	Visibility           string             `json:"visibility"`
	Status               string             `json:"status"`
	CreatedAt            time.Time          `json:"created_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	IsSystem             bool               `json:"is_system"`
	Language             string             `json:"language"`
	GroupID              pgtype.UUID        `json:"group_id"`
	Classification       string             `json:"classification"`
	DuplicatedFromPackID pgtype.UUID        `json:"duplicated_from_pack_id"`
	DuplicatedByUserID   pgtype.UUID        `json:"duplicated_by_user_id"`
}

type GameType struct {
	ID           uuid.UUID       `json:"id"`
	Slug         string          `json:"slug"`
	Name         string          `json:"name"`
	Description  *string         `json:"description"`
	Version      string          `json:"version"`
	SupportsSolo bool            `json:"supports_solo"`
	Config       json.RawMessage `json:"config"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Group struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	NameNormalized *string            `json:"name_normalized"`
	Description    string             `json:"description"`
	AvatarMediaKey *string            `json:"avatar_media_key"`
	Language       string             `json:"language"`
	Classification string             `json:"classification"`
	MemberCap      int32              `json:"member_cap"`
	QuotaBytes     int64              `json:"quota_bytes"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type GroupBan struct {
	ID       uuid.UUID   `json:"id"`
	GroupID  uuid.UUID   `json:"group_id"`
	UserID   uuid.UUID   `json:"user_id"`
	BannedBy pgtype.UUID `json:"banned_by"`
	BannedAt time.Time   `json:"banned_at"`
}

type GroupDuplicationPending struct {
	ID           uuid.UUID          `json:"id"`
	GroupID      uuid.UUID          `json:"group_id"`
	SourcePackID uuid.UUID          `json:"source_pack_id"`
	RequestedBy  uuid.UUID          `json:"requested_by"`
	RequestedAt  time.Time          `json:"requested_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy   pgtype.UUID        `json:"resolved_by"`
	Resolution   *string            `json:"resolution"`
}

type GroupInvite struct {
	ID              uuid.UUID          `json:"id"`
	Token           string             `json:"token"`
	GroupID         uuid.UUID          `json:"group_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Kind            string             `json:"kind"`
	RestrictedEmail *string            `json:"restricted_email"`
	MaxUses         int32              `json:"max_uses"`
	UsesCount       int32              `json:"uses_count"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type GroupMembership struct {
	ID       uuid.UUID `json:"id"`
	GroupID  uuid.UUID `json:"group_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

type GroupNotification struct {
	ID        uuid.UUID          `json:"id"`
	GroupID   uuid.UUID          `json:"group_id"`
	Type      string             `json:"type"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	SubjectID pgtype.UUID        `json:"subject_id"`
	Payload   json.RawMessage    `json:"payload"`
	CreatedAt time.Time          `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type GuestPlayer struct {
	ID          uuid.UUID `json:"id"`
	RoomID      uuid.UUID `json:"room_id"`
	DisplayName string    `json:"display_name"`
	TokenHash   string    `json:"token_hash"`
	CreatedAt   time.Time `json:"created_at"`
	LastSeenAt  time.Time `json:"last_seen_at"`
}

type Invite struct {
	ID              uuid.UUID          `json:"id"`
	Token           string             `json:"token"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Label           *string            `json:"label"`
	RestrictedEmail *string            `json:"restricted_email"`
	MaxUses         int32              `json:"max_uses"`
	UsesCount       int32              `json:"uses_count"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       time.Time          `json:"created_at"`
	Locale          string             `json:"locale"`
}

type MagicLinkToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Room struct {
	ID                     uuid.UUID          `json:"id"`
	Code                   string             `json:"code"`
	GameTypeID             uuid.UUID          `json:"game_type_id"`
	HostID                 pgtype.UUID        `json:"host_id"`
	Mode                   string             `json:"mode"`
	State                  string             `json:"state"`
	Config                 json.RawMessage    `json:"config"`
	CreatedAt              time.Time          `json:"created_at"`
	FinishedAt             pgtype.Timestamptz `json:"finished_at"`
	RematchWindowExpiresAt pgtype.Timestamptz `json:"rematch_window_expires_at"`
	GroupID                pgtype.UUID        `json:"group_id"`
}

type RoomBan struct {
	ID            uuid.UUID   `json:"id"`
	RoomID        uuid.UUID   `json:"room_id"`
	UserID        pgtype.UUID `json:"user_id"`
	GuestPlayerID pgtype.UUID `json:"guest_player_id"`
	BannedBy      pgtype.UUID `json:"banned_by"`
	BannedAt      time.Time   `json:"banned_at"`
}

type RoomPack struct {
	RoomID uuid.UUID `json:"room_id"`
	Role   string    `json:"role"`
	PackID uuid.UUID `json:"pack_id"`
	Weight int32     `json:"weight"`
}

type RoomPlayer struct {
	RoomID        uuid.UUID   `json:"room_id"`
	UserID        pgtype.UUID `json:"user_id"`
	Score         int32       `json:"score"`
	JoinedAt      time.Time   `json:"joined_at"`
	GuestPlayerID pgtype.UUID `json:"guest_player_id"`
}

type Round struct {
	ID          uuid.UUID          `json:"id"`
	RoomID      uuid.UUID          `json:"room_id"`
	ItemID      uuid.UUID          `json:"item_id"`
	RoundNumber int32              `json:"round_number"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Submission struct {
	ID            uuid.UUID       `json:"id"`
	RoundID       uuid.UUID       `json:"round_id"`
	UserID        pgtype.UUID     `json:"user_id"`
	Payload       json.RawMessage `json:"payload"`
	CreatedAt     time.Time       `json:"created_at"`
	GuestPlayerID pgtype.UUID     `json:"guest_player_id"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PendingEmail *string            `json:"pending_email"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	InvitedBy    pgtype.UUID        `json:"invited_by"`
	ConsentAt    time.Time          `json:"consent_at"`
	CreatedAt    time.Time          `json:"created_at"`
	IsProtected  bool               `json:"is_protected"`
	Locale       string             `json:"locale"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

type UserInviteQuota struct {
	UserID    uuid.UUID `json:"user_id"`
	Allocated int32     `json:"allocated"`
	Used      int32     `json:"used"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Vote struct {
	ID           uuid.UUID       `json:"id"`
	SubmissionID uuid.UUID       `json:"submission_id"`
	VoterID      pgtype.UUID     `json:"voter_id"`
	Value        json.RawMessage `json:"value"`
	CreatedAt    time.Time       `json:"created_at"`
	GuestVoterID pgtype.UUID     `json:"guest_voter_id"`
}
