// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminNotification struct {
	ID        uuid.UUID          `json:"id"`
	Type      string             `json:"type"`
	PackID    pgtype.UUID        `json:"pack_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	CreatedAt time.Time          `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type AuditLog struct {
	ID        uuid.UUID       `json:"id"`
	AdminID   pgtype.UUID     `json:"admin_id"`
	Action    string          `json:"action"`
	Resource  string          `json:"resource"`
	Changes   json.RawMessage `json:"changes"`
	CreatedAt time.Time       `json:"created_at"`
}

type GameItem struct {
	ID               uuid.UUID   `json:"id"`
	PackID           uuid.UUID   `json:"pack_id"`
	Position         int32       `json:"position"`
	PayloadVersion   int32       `json:"payload_version"`
	CurrentVersionID pgtype.UUID `json:"current_version_id"`
	CreatedAt        time.Time   `json:"created_at"`
}

type GameItemVersion struct {
	ID            uuid.UUID          `json:"id"`
	ItemID        uuid.UUID          `json:"item_id"`
	VersionNumber int32              `json:"version_number"`
	MediaKey      *string            `json:"media_key"`
	Payload       json.RawMessage    `json:"payload"`
	CreatedAt     time.Time          `json:"created_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type GamePack struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	IsOfficial  bool               `json:"is_official"`
	Visibility  string             `json:"visibility"`
	Status      string             `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type GameType struct {
	ID           uuid.UUID       `json:"id"`
	Slug         string          `json:"slug"`
	Name         string          `json:"name"`
	Description  *string         `json:"description"`
	Version      string          `json:"version"`
	SupportsSolo bool            `json:"supports_solo"`
	Config       json.RawMessage `json:"config"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Invite struct {
	ID              uuid.UUID          `json:"id"`
	Token           string             `json:"token"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Label           *string            `json:"label"`
	RestrictedEmail *string            `json:"restricted_email"`
	MaxUses         int32              `json:"max_uses"`
	UsesCount       int32              `json:"uses_count"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type MagicLinkToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Room struct {
	ID         uuid.UUID          `json:"id"`
	Code       string             `json:"code"`
	GameTypeID uuid.UUID          `json:"game_type_id"`
	PackID     uuid.UUID          `json:"pack_id"`
	HostID     pgtype.UUID        `json:"host_id"`
	Mode       string             `json:"mode"`
	State      string             `json:"state"`
	Config     json.RawMessage    `json:"config"`
	CreatedAt  time.Time          `json:"created_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type RoomPlayer struct {
	RoomID   uuid.UUID `json:"room_id"`
	UserID   uuid.UUID `json:"user_id"`
	Score    int32     `json:"score"`
	JoinedAt time.Time `json:"joined_at"`
}

type Round struct {
	ID          uuid.UUID          `json:"id"`
	RoomID      uuid.UUID          `json:"room_id"`
	ItemID      uuid.UUID          `json:"item_id"`
	RoundNumber int32              `json:"round_number"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Submission struct {
	ID        uuid.UUID       `json:"id"`
	RoundID   uuid.UUID       `json:"round_id"`
	UserID    uuid.UUID       `json:"user_id"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PendingEmail *string     `json:"pending_email"`
	Role         string      `json:"role"`
	IsActive     bool        `json:"is_active"`
	InvitedBy    pgtype.UUID `json:"invited_by"`
	ConsentAt    time.Time   `json:"consent_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Vote struct {
	ID           uuid.UUID       `json:"id"`
	SubmissionID uuid.UUID       `json:"submission_id"`
	VoterID      uuid.UUID       `json:"voter_id"`
	Value        json.RawMessage `json:"value"`
	CreatedAt    time.Time       `json:"created_at"`
}
