// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const dangerDeleteAllAdminNotifications = `-- name: DangerDeleteAllAdminNotifications :many
DELETE FROM admin_notifications RETURNING id
`

func (q *Queries) DangerDeleteAllAdminNotifications(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllAdminNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllGameItemVersions = `-- name: DangerDeleteAllGameItemVersions :many
DELETE FROM game_item_versions RETURNING id
`

// Items cascade from packs, versions cascade from items, so in practice
// this count is only interesting if packs are NOT being deleted. Kept as
// a separate query so the Report can still surface a version count when
// WipePacksAndMedia runs.
func (q *Queries) DangerDeleteAllGameItemVersions(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllGameItemVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllGameItems = `-- name: DangerDeleteAllGameItems :many
DELETE FROM game_items RETURNING id
`

func (q *Queries) DangerDeleteAllGameItems(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllGameItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllGamePacks = `-- name: DangerDeleteAllGamePacks :many
DELETE FROM game_packs RETURNING id
`

func (q *Queries) DangerDeleteAllGamePacks(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllGamePacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllInvites = `-- name: DangerDeleteAllInvites :many
DELETE FROM invites RETURNING id
`

func (q *Queries) DangerDeleteAllInvites(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllMagicLinkTokens = `-- name: DangerDeleteAllMagicLinkTokens :many
DELETE FROM magic_link_tokens RETURNING id
`

func (q *Queries) DangerDeleteAllMagicLinkTokens(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllMagicLinkTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllRoomPlayers = `-- name: DangerDeleteAllRoomPlayers :many
DELETE FROM room_players RETURNING room_id
`

func (q *Queries) DangerDeleteAllRoomPlayers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllRoomPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var room_id uuid.UUID
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllRooms = `-- name: DangerDeleteAllRooms :many
DELETE FROM rooms RETURNING id
`

func (q *Queries) DangerDeleteAllRooms(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllRounds = `-- name: DangerDeleteAllRounds :many
DELETE FROM rounds RETURNING id
`

func (q *Queries) DangerDeleteAllRounds(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllRounds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllSubmissions = `-- name: DangerDeleteAllSubmissions :many
DELETE FROM submissions RETURNING id
`

func (q *Queries) DangerDeleteAllSubmissions(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllSubmissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteAllVotes = `-- name: DangerDeleteAllVotes :many

DELETE FROM votes RETURNING id
`

// backend/db/queries/reset.sql
//
// Queries for the destructive admin actions ("danger zone"). Each query
// returns the deleted ids so the service layer can count without an
// extra COUNT round-trip. All queries assume they run inside a caller-
// owned transaction.
func (q *Queries) DangerDeleteAllVotes(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteAllVotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteNonProtectedUsersExcept = `-- name: DangerDeleteNonProtectedUsersExcept :many
DELETE FROM users
WHERE id != '00000000-0000-0000-0000-000000000001'::uuid
  AND is_protected = false
  AND id != $1
RETURNING id
`

// Preserves: sentinel user, any user with is_protected=true, and the
// acting admin (passed as $1).
func (q *Queries) DangerDeleteNonProtectedUsersExcept(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteNonProtectedUsersExcept, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dangerDeleteSessionsExcept = `-- name: DangerDeleteSessionsExcept :many
DELETE FROM sessions WHERE user_id != $1 RETURNING id
`

// Wipe every session except the acting admin's. Pass uuid.Nil to wipe all.
func (q *Queries) DangerDeleteSessionsExcept(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dangerDeleteSessionsExcept, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
