// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGuestRoomPlayer = `-- name: AddGuestRoomPlayer :one
INSERT INTO room_players (room_id, guest_player_id) VALUES ($1, $2) RETURNING room_id, user_id, score, joined_at, guest_player_id
`

type AddGuestRoomPlayerParams struct {
	RoomID        uuid.UUID   `json:"room_id"`
	GuestPlayerID pgtype.UUID `json:"guest_player_id"`
}

func (q *Queries) AddGuestRoomPlayer(ctx context.Context, arg AddGuestRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, addGuestRoomPlayer, arg.RoomID, arg.GuestPlayerID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
		&i.GuestPlayerID,
	)
	return i, err
}

const addRoomPlayer = `-- name: AddRoomPlayer :one
INSERT INTO room_players (room_id, user_id) VALUES ($1, $2) RETURNING room_id, user_id, score, joined_at, guest_player_id
`

type AddRoomPlayerParams struct {
	RoomID uuid.UUID   `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddRoomPlayer(ctx context.Context, arg AddRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, addRoomPlayer, arg.RoomID, arg.UserID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
		&i.GuestPlayerID,
	)
	return i, err
}

const countActiveRooms = `-- name: CountActiveRooms :one
SELECT COUNT(*) FROM rooms WHERE state IN ('lobby', 'playing')
`

// Counts rooms currently in lobby or playing state. Used by the admin dashboard
// stats card. Finished rooms are excluded — operators care about live activity.
func (q *Queries) CountActiveRooms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRooms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFinishedRooms = `-- name: CountFinishedRooms :one
SELECT COUNT(*) FROM rooms WHERE state = 'finished'
`

// Counts rooms that reached the 'finished' state — i.e. a played-to-completion
// game. Used by the admin dashboard "Total Games Played" card. Rooms that
// were abandoned in lobby and auto-closed by startup cleanup are also in
// this state, but at this scale the signal is close enough to "real games".
func (q *Queries) CountFinishedRooms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFinishedRooms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuestRoomBan = `-- name: CreateGuestRoomBan :exec
INSERT INTO room_bans (room_id, guest_player_id, banned_by)
VALUES ($1, $2, $3)
ON CONFLICT (room_id, guest_player_id) WHERE guest_player_id IS NOT NULL DO NOTHING
`

type CreateGuestRoomBanParams struct {
	RoomID        uuid.UUID   `json:"room_id"`
	GuestPlayerID pgtype.UUID `json:"guest_player_id"`
	BannedBy      pgtype.UUID `json:"banned_by"`
}

// Records a guest's ban in this room, keyed by guest_player_id. The guest's
// existing token becomes useless for this room; a fresh guest-join with a
// new display name mints a new guest_player_id and is not blocked
// (accepted limitation — see spec non-goals).
func (q *Queries) CreateGuestRoomBan(ctx context.Context, arg CreateGuestRoomBanParams) error {
	_, err := q.db.Exec(ctx, createGuestRoomBan, arg.RoomID, arg.GuestPlayerID, arg.BannedBy)
	return err
}

const createGuestSubmission = `-- name: CreateGuestSubmission :one
INSERT INTO submissions (round_id, guest_player_id, payload) VALUES ($1, $2, $3) RETURNING id, round_id, user_id, payload, created_at, guest_player_id
`

type CreateGuestSubmissionParams struct {
	RoundID       uuid.UUID       `json:"round_id"`
	GuestPlayerID pgtype.UUID     `json:"guest_player_id"`
	Payload       json.RawMessage `json:"payload"`
}

func (q *Queries) CreateGuestSubmission(ctx context.Context, arg CreateGuestSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createGuestSubmission, arg.RoundID, arg.GuestPlayerID, arg.Payload)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.UserID,
		&i.Payload,
		&i.CreatedAt,
		&i.GuestPlayerID,
	)
	return i, err
}

const createGuestVote = `-- name: CreateGuestVote :one
INSERT INTO votes (submission_id, guest_voter_id, value) VALUES ($1, $2, $3) RETURNING id, submission_id, voter_id, value, created_at, guest_voter_id
`

type CreateGuestVoteParams struct {
	SubmissionID uuid.UUID       `json:"submission_id"`
	GuestVoterID pgtype.UUID     `json:"guest_voter_id"`
	Value        json.RawMessage `json:"value"`
}

func (q *Queries) CreateGuestVote(ctx context.Context, arg CreateGuestVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createGuestVote, arg.SubmissionID, arg.GuestVoterID, arg.Value)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.VoterID,
		&i.Value,
		&i.CreatedAt,
		&i.GuestVoterID,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one

INSERT INTO rooms (code, game_type_id, pack_id, text_pack_id, host_id, mode, config)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code, game_type_id, pack_id, host_id, mode, state, config, created_at, finished_at, rematch_window_expires_at, text_pack_id
`

type CreateRoomParams struct {
	Code       string          `json:"code"`
	GameTypeID uuid.UUID       `json:"game_type_id"`
	PackID     uuid.UUID       `json:"pack_id"`
	TextPackID pgtype.UUID     `json:"text_pack_id"`
	HostID     pgtype.UUID     `json:"host_id"`
	Mode       string          `json:"mode"`
	Config     json.RawMessage `json:"config"`
}

// backend/db/queries/rooms.sql
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Code,
		arg.GameTypeID,
		arg.PackID,
		arg.TextPackID,
		arg.HostID,
		arg.Mode,
		arg.Config,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameTypeID,
		&i.PackID,
		&i.HostID,
		&i.Mode,
		&i.State,
		&i.Config,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.RematchWindowExpiresAt,
		&i.TextPackID,
	)
	return i, err
}

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (room_id, item_id, round_number)
SELECT $1, $2, COALESCE(MAX(round_number), 0) + 1 FROM rounds WHERE room_id = $1
RETURNING id, room_id, item_id, round_number, started_at, ended_at
`

type CreateRoundParams struct {
	RoomID uuid.UUID `json:"room_id"`
	ItemID uuid.UUID `json:"item_id"`
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, createRound, arg.RoomID, arg.ItemID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ItemID,
		&i.RoundNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (round_id, user_id, payload) VALUES ($1, $2, $3) RETURNING id, round_id, user_id, payload, created_at, guest_player_id
`

type CreateSubmissionParams struct {
	RoundID uuid.UUID       `json:"round_id"`
	UserID  pgtype.UUID     `json:"user_id"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission, arg.RoundID, arg.UserID, arg.Payload)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.UserID,
		&i.Payload,
		&i.CreatedAt,
		&i.GuestPlayerID,
	)
	return i, err
}

const createUserRoomBan = `-- name: CreateUserRoomBan :exec
INSERT INTO room_bans (room_id, user_id, banned_by)
VALUES ($1, $2, $3)
ON CONFLICT (room_id, user_id) WHERE user_id IS NOT NULL DO NOTHING
`

type CreateUserRoomBanParams struct {
	RoomID   uuid.UUID   `json:"room_id"`
	UserID   pgtype.UUID `json:"user_id"`
	BannedBy pgtype.UUID `json:"banned_by"`
}

// Records a registered user's ban in this room. Idempotent: a duplicate
// kick is a no-op. Caller provides banned_by = session user ID (or admin
// acting on the room). See docs/superpowers/specs/2026-04-18-lobby-kick-and-ban-design.md.
func (q *Queries) CreateUserRoomBan(ctx context.Context, arg CreateUserRoomBanParams) error {
	_, err := q.db.Exec(ctx, createUserRoomBan, arg.RoomID, arg.UserID, arg.BannedBy)
	return err
}

const createVote = `-- name: CreateVote :one
INSERT INTO votes (submission_id, voter_id, value) VALUES ($1, $2, $3) RETURNING id, submission_id, voter_id, value, created_at, guest_voter_id
`

type CreateVoteParams struct {
	SubmissionID uuid.UUID       `json:"submission_id"`
	VoterID      pgtype.UUID     `json:"voter_id"`
	Value        json.RawMessage `json:"value"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote, arg.SubmissionID, arg.VoterID, arg.Value)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.VoterID,
		&i.Value,
		&i.CreatedAt,
		&i.GuestVoterID,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1
`

// Hard-deletes a room and everything that references it via ON DELETE CASCADE:
// room_players, guest_players, rounds, submissions, votes. Used by the cancel
// path (POST /rooms/{code}/end) so a cancelled room vanishes from history and
// leaderboard as if it was never created. Naturally-finished rooms keep using
// SetRoomState so post-game history still works.
func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const endRound = `-- name: EndRound :one
UPDATE rounds SET ended_at = now() WHERE id = $1 RETURNING id, room_id, item_id, round_number, started_at, ended_at
`

func (q *Queries) EndRound(ctx context.Context, id uuid.UUID) (Round, error) {
	row := q.db.QueryRow(ctx, endRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ItemID,
		&i.RoundNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const finishAbandonedLobbies = `-- name: FinishAbandonedLobbies :execresult
UPDATE rooms SET state = 'finished', finished_at = now()
WHERE state = 'lobby' AND created_at < now() - interval '24 hours'
`

func (q *Queries) FinishAbandonedLobbies(ctx context.Context) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, finishAbandonedLobbies)
}

const finishCrashedRooms = `-- name: FinishCrashedRooms :execresult
UPDATE rooms SET state = 'finished', finished_at = now() WHERE state = 'playing'
`

func (q *Queries) FinishCrashedRooms(ctx context.Context) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, finishCrashedRooms)
}

const getActiveRoomForUser = `-- name: GetActiveRoomForUser :one
SELECT r.id, r.code, r.state, gt.slug::text AS game_type_slug, TRUE AS is_host
FROM rooms r
JOIN game_types gt ON r.game_type_id = gt.id
WHERE r.host_id = $1 AND r.state IN ('lobby','playing')
UNION ALL
SELECT r.id, r.code, r.state, gt.slug::text AS game_type_slug, FALSE AS is_host
FROM room_players rp
JOIN rooms r ON rp.room_id = r.id
JOIN game_types gt ON r.game_type_id = gt.id
WHERE rp.user_id = $1 AND r.state IN ('lobby','playing')
LIMIT 1
`

type GetActiveRoomForUserRow struct {
	ID           uuid.UUID `json:"id"`
	Code         string    `json:"code"`
	State        string    `json:"state"`
	GameTypeSlug string    `json:"game_type_slug"`
	IsHost       bool      `json:"is_host"`
}

// Returns the single lobby/playing room the user is bound to, as either host
// or participant. Returns no rows if the user is free. The two legs are
// mutually exclusive in practice because RoomHandler.Create upserts the host
// into room_players on creation — if both somehow match, prefer the host row
// (listed first in the UNION).
func (q *Queries) GetActiveRoomForUser(ctx context.Context, hostID pgtype.UUID) (GetActiveRoomForUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveRoomForUser, hostID)
	var i GetActiveRoomForUserRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.State,
		&i.GameTypeSlug,
		&i.IsHost,
	)
	return i, err
}

const getCurrentRound = `-- name: GetCurrentRound :one
SELECT id, room_id, item_id, round_number, started_at, ended_at FROM rounds WHERE room_id = $1 AND started_at IS NOT NULL AND ended_at IS NULL
ORDER BY round_number DESC LIMIT 1
`

func (q *Queries) GetCurrentRound(ctx context.Context, roomID uuid.UUID) (Round, error) {
	row := q.db.QueryRow(ctx, getCurrentRound, roomID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ItemID,
		&i.RoundNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getFinishedRoomByCode = `-- name: GetFinishedRoomByCode :one
SELECT
  r.id,
  r.code,
  r.host_id,
  r.state,
  r.config,
  r.created_at AS started_at,
  r.finished_at,
  gt.slug::text                            AS game_type_slug,
  gp.name::text                            AS pack_name,
  COALESCE(tp.name, '')::text              AS text_pack_name,
  (SELECT COUNT(*) FROM room_players rp WHERE rp.room_id = r.id)::bigint AS player_count
FROM rooms r
JOIN game_types gt ON r.game_type_id = gt.id
JOIN game_packs gp ON r.pack_id = gp.id
LEFT JOIN game_packs tp ON r.text_pack_id = tp.id
WHERE r.code = $1 AND r.state = 'finished'
`

type GetFinishedRoomByCodeRow struct {
	ID           uuid.UUID          `json:"id"`
	Code         string             `json:"code"`
	HostID       pgtype.UUID        `json:"host_id"`
	State        string             `json:"state"`
	Config       json.RawMessage    `json:"config"`
	StartedAt    time.Time          `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	GameTypeSlug string             `json:"game_type_slug"`
	PackName     string             `json:"pack_name"`
	TextPackName string             `json:"text_pack_name"`
	PlayerCount  int64              `json:"player_count"`
}

// Replay landing lookup. Returns public room metadata plus slug/pack names.
// text_pack_name is the empty string when the game type has no text pack.
func (q *Queries) GetFinishedRoomByCode(ctx context.Context, code string) (GetFinishedRoomByCodeRow, error) {
	row := q.db.QueryRow(ctx, getFinishedRoomByCode, code)
	var i GetFinishedRoomByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostID,
		&i.State,
		&i.Config,
		&i.StartedAt,
		&i.FinishedAt,
		&i.GameTypeSlug,
		&i.PackName,
		&i.TextPackName,
		&i.PlayerCount,
	)
	return i, err
}

const getRecentRoomsForUser = `-- name: GetRecentRoomsForUser :many
SELECT
  r.id,
  r.code,
  r.state,
  r.created_at,
  r.finished_at,
  gt.slug AS game_type_slug,
  gp.name AS pack_name
FROM room_players rp
JOIN rooms r ON rp.room_id = r.id
JOIN game_types gt ON r.game_type_id = gt.id
JOIN game_packs gp ON r.pack_id = gp.id
WHERE rp.user_id = $1
  AND r.created_at > now() - interval '30 days'
ORDER BY r.created_at DESC
LIMIT $2
`

type GetRecentRoomsForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type GetRecentRoomsForUserRow struct {
	ID           uuid.UUID          `json:"id"`
	Code         string             `json:"code"`
	State        string             `json:"state"`
	CreatedAt    time.Time          `json:"created_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	GameTypeSlug string             `json:"game_type_slug"`
	PackName     string             `json:"pack_name"`
}

// Powers the "Recent rooms" strip on the new Home page. Scoped to the session
// user — never take a user_id parameter from the client. Participation is
// detected via room_players join so both hosts and non-host players qualify.
func (q *Queries) GetRecentRoomsForUser(ctx context.Context, arg GetRecentRoomsForUserParams) ([]GetRecentRoomsForUserRow, error) {
	rows, err := q.db.Query(ctx, getRecentRoomsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentRoomsForUserRow
	for rows.Next() {
		var i GetRecentRoomsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.State,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.GameTypeSlug,
			&i.PackName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplayLeaderboard = `-- name: GetReplayLeaderboard :many
SELECT
  COALESCE(rp.user_id, rp.guest_player_id)::uuid AS player_id,
  COALESCE(u.username, gp.display_name, '[deleted]')::text AS display_name,
  CASE
    WHEN u.id = '00000000-0000-0000-0000-000000000001' THEN 'deleted'
    WHEN rp.guest_player_id IS NOT NULL                THEN 'guest'
    ELSE 'user'
  END::text                                      AS kind,
  rp.score
FROM room_players rp
LEFT JOIN users u         ON rp.user_id = u.id
LEFT JOIN guest_players gp ON rp.guest_player_id = gp.id
WHERE rp.room_id = $1
ORDER BY rp.score DESC, rp.joined_at ASC
`

type GetReplayLeaderboardRow struct {
	PlayerID    uuid.UUID `json:"player_id"`
	DisplayName string    `json:"display_name"`
	Kind        string    `json:"kind"`
	Score       int32     `json:"score"`
}

// Final room_players leaderboard, sorted by score. Rank is assigned in Go
// so tie-handling matches the live ResultsView (dense rank).
func (q *Queries) GetReplayLeaderboard(ctx context.Context, roomID uuid.UUID) ([]GetReplayLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getReplayLeaderboard, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReplayLeaderboardRow
	for rows.Next() {
		var i GetReplayLeaderboardRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.DisplayName,
			&i.Kind,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplayRounds = `-- name: GetReplayRounds :many
SELECT
  rnd.id              AS round_id,
  rnd.round_number,
  rnd.started_at,
  rnd.ended_at,
  gi.payload_version  AS prompt_payload_version,
  giv.media_key       AS prompt_media_key,
  giv.payload         AS prompt_payload
FROM rounds rnd
JOIN game_items gi ON rnd.item_id = gi.id
JOIN game_item_versions giv ON gi.current_version_id = giv.id
WHERE rnd.room_id = $1
ORDER BY rnd.round_number
`

type GetReplayRoundsRow struct {
	RoundID              uuid.UUID          `json:"round_id"`
	RoundNumber          int32              `json:"round_number"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	EndedAt              pgtype.Timestamptz `json:"ended_at"`
	PromptPayloadVersion int32              `json:"prompt_payload_version"`
	PromptMediaKey       *string            `json:"prompt_media_key"`
	PromptPayload        json.RawMessage    `json:"prompt_payload"`
}

// All rounds for the room, ordered by round_number. Every row in `rounds`
// corresponds to a round the engine actually began (CreateRound is the first
// step of the per-round loop); abandoned lobbies never populate this table.
// Joins the prompt item's current version so the frontend gets the full
// payload (image media_key, caption prompt, text) without a second round-trip.
func (q *Queries) GetReplayRounds(ctx context.Context, roomID uuid.UUID) ([]GetReplayRoundsRow, error) {
	rows, err := q.db.Query(ctx, getReplayRounds, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReplayRoundsRow
	for rows.Next() {
		var i GetReplayRoundsRow
		if err := rows.Scan(
			&i.RoundID,
			&i.RoundNumber,
			&i.StartedAt,
			&i.EndedAt,
			&i.PromptPayloadVersion,
			&i.PromptMediaKey,
			&i.PromptPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplaySubmissions = `-- name: GetReplaySubmissions :many
SELECT
  s.id                                                           AS submission_id,
  s.round_id,
  s.payload,
  COALESCE(u.username, gp.display_name, '[deleted]')::text       AS author_name,
  CASE
    WHEN u.id = '00000000-0000-0000-0000-000000000001' THEN 'deleted'
    WHEN s.guest_player_id IS NOT NULL                   THEN 'guest'
    ELSE 'user'
  END::text                                                      AS author_kind,
  (SELECT COUNT(*) FROM votes v WHERE v.submission_id = s.id)::int AS votes_received
FROM submissions s
JOIN rounds rnd ON s.round_id = rnd.id
LEFT JOIN users u         ON s.user_id = u.id
LEFT JOIN guest_players gp ON s.guest_player_id = gp.id
WHERE rnd.room_id = $1
ORDER BY rnd.round_number, s.created_at
`

type GetReplaySubmissionsRow struct {
	SubmissionID  uuid.UUID       `json:"submission_id"`
	RoundID       uuid.UUID       `json:"round_id"`
	Payload       json.RawMessage `json:"payload"`
	AuthorName    string          `json:"author_name"`
	AuthorKind    string          `json:"author_kind"`
	VotesReceived int32           `json:"votes_received"`
}

// Submissions for every round of the room, with author resolution across
// users and guests. Sentinel rows (hard-deleted users) surface as
// display_name='[deleted]', kind='deleted'. votes_received is a subquery
// count per submission.
func (q *Queries) GetReplaySubmissions(ctx context.Context, roomID uuid.UUID) ([]GetReplaySubmissionsRow, error) {
	rows, err := q.db.Query(ctx, getReplaySubmissions, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReplaySubmissionsRow
	for rows.Next() {
		var i GetReplaySubmissionsRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.RoundID,
			&i.Payload,
			&i.AuthorName,
			&i.AuthorKind,
			&i.VotesReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT r.id, r.code, r.game_type_id, r.pack_id, r.host_id, r.mode, r.state, r.config, r.created_at, r.finished_at, r.rematch_window_expires_at, r.text_pack_id, gt.slug AS game_type_slug FROM rooms r
JOIN game_types gt ON r.game_type_id = gt.id
WHERE r.code = $1
`

type GetRoomByCodeRow struct {
	ID                     uuid.UUID          `json:"id"`
	Code                   string             `json:"code"`
	GameTypeID             uuid.UUID          `json:"game_type_id"`
	PackID                 uuid.UUID          `json:"pack_id"`
	HostID                 pgtype.UUID        `json:"host_id"`
	Mode                   string             `json:"mode"`
	State                  string             `json:"state"`
	Config                 json.RawMessage    `json:"config"`
	CreatedAt              time.Time          `json:"created_at"`
	FinishedAt             pgtype.Timestamptz `json:"finished_at"`
	RematchWindowExpiresAt pgtype.Timestamptz `json:"rematch_window_expires_at"`
	TextPackID             pgtype.UUID        `json:"text_pack_id"`
	GameTypeSlug           string             `json:"game_type_slug"`
}

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (GetRoomByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i GetRoomByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameTypeID,
		&i.PackID,
		&i.HostID,
		&i.Mode,
		&i.State,
		&i.Config,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.RematchWindowExpiresAt,
		&i.TextPackID,
		&i.GameTypeSlug,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, code, game_type_id, pack_id, host_id, mode, state, config, created_at, finished_at, rematch_window_expires_at, text_pack_id FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameTypeID,
		&i.PackID,
		&i.HostID,
		&i.Mode,
		&i.State,
		&i.Config,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.RematchWindowExpiresAt,
		&i.TextPackID,
	)
	return i, err
}

const getRoomLeaderboard = `-- name: GetRoomLeaderboard :many
SELECT
  COALESCE(rp.user_id, rp.guest_player_id)::uuid AS player_id,
  COALESCE(u.username, gp.display_name)::text AS display_name,
  (rp.guest_player_id IS NOT NULL)::bool AS is_guest,
  rp.score,
  RANK() OVER (ORDER BY rp.score DESC) AS rank
FROM room_players rp
LEFT JOIN users u ON rp.user_id = u.id
LEFT JOIN guest_players gp ON rp.guest_player_id = gp.id
WHERE rp.room_id = $1
ORDER BY rp.score DESC
`

type GetRoomLeaderboardRow struct {
	PlayerID    uuid.UUID `json:"player_id"`
	DisplayName string    `json:"display_name"`
	IsGuest     bool      `json:"is_guest"`
	Score       int32     `json:"score"`
	Rank        int64     `json:"rank"`
}

// Unified leaderboard over users and guests. player_id is the UUID of whichever
// kind of player the row represents; display_name coalesces across users.username
// and guest_players.display_name; is_guest lets the client render a badge.
func (q *Queries) GetRoomLeaderboard(ctx context.Context, roomID uuid.UUID) ([]GetRoomLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getRoomLeaderboard, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomLeaderboardRow
	for rows.Next() {
		var i GetRoomLeaderboardRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.DisplayName,
			&i.IsGuest,
			&i.Score,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomPlayer = `-- name: GetRoomPlayer :one
SELECT room_id, user_id, score, joined_at, guest_player_id FROM room_players WHERE room_id = $1 AND user_id = $2
`

type GetRoomPlayerParams struct {
	RoomID uuid.UUID   `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetRoomPlayer(ctx context.Context, arg GetRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, getRoomPlayer, arg.RoomID, arg.UserID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
		&i.GuestPlayerID,
	)
	return i, err
}

const getSubmissionsForRound = `-- name: GetSubmissionsForRound :many
SELECT id, round_id, user_id, payload, created_at, guest_player_id FROM submissions WHERE round_id = $1
`

func (q *Queries) GetSubmissionsForRound(ctx context.Context, roundID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, getSubmissionsForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.UserID,
			&i.Payload,
			&i.CreatedAt,
			&i.GuestPlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteByVoterInRound = `-- name: GetVoteByVoterInRound :one
SELECT v.id, v.submission_id, v.voter_id, v.value, v.created_at, v.guest_voter_id FROM votes v
JOIN submissions s ON v.submission_id = s.id
WHERE s.round_id = $1 AND v.voter_id = $2
`

type GetVoteByVoterInRoundParams struct {
	RoundID uuid.UUID   `json:"round_id"`
	VoterID pgtype.UUID `json:"voter_id"`
}

func (q *Queries) GetVoteByVoterInRound(ctx context.Context, arg GetVoteByVoterInRoundParams) (Vote, error) {
	row := q.db.QueryRow(ctx, getVoteByVoterInRound, arg.RoundID, arg.VoterID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.VoterID,
		&i.Value,
		&i.CreatedAt,
		&i.GuestVoterID,
	)
	return i, err
}

const getVotesForRound = `-- name: GetVotesForRound :many
SELECT v.id, v.submission_id, v.voter_id, v.value, v.created_at, v.guest_voter_id FROM votes v
JOIN submissions s ON v.submission_id = s.id
WHERE s.round_id = $1
`

func (q *Queries) GetVotesForRound(ctx context.Context, roundID uuid.UUID) ([]Vote, error) {
	rows, err := q.db.Query(ctx, getVotesForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.VoterID,
			&i.Value,
			&i.CreatedAt,
			&i.GuestVoterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isGuestBannedFromRoom = `-- name: IsGuestBannedFromRoom :one
SELECT EXISTS(
  SELECT 1 FROM room_bans WHERE room_id = $1 AND guest_player_id = $2
)
`

type IsGuestBannedFromRoomParams struct {
	RoomID        uuid.UUID   `json:"room_id"`
	GuestPlayerID pgtype.UUID `json:"guest_player_id"`
}

// Used by the WS handshake after a guest token resolves to a guest_player_id.
func (q *Queries) IsGuestBannedFromRoom(ctx context.Context, arg IsGuestBannedFromRoomParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGuestBannedFromRoom, arg.RoomID, arg.GuestPlayerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserBannedFromRoom = `-- name: IsUserBannedFromRoom :one
SELECT EXISTS(
  SELECT 1 FROM room_bans WHERE room_id = $1 AND user_id = $2
)
`

type IsUserBannedFromRoomParams struct {
	RoomID uuid.UUID   `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Used by the WS handshake to reject a registered user's (re)join.
func (q *Queries) IsUserBannedFromRoom(ctx context.Context, arg IsUserBannedFromRoomParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBannedFromRoom, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserRoomMember = `-- name: IsUserRoomMember :one
SELECT EXISTS(
  SELECT 1 FROM room_players
  WHERE room_id = $1 AND user_id = $2
)::bool
`

type IsUserRoomMemberParams struct {
	RoomID uuid.UUID   `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Authorization check for replay: returns TRUE iff this user participated in
// the room as a registered player. Guests are never members for this purpose
// (they have no login); admins bypass in the handler.
func (q *Queries) IsUserRoomMember(ctx context.Context, arg IsUserRoomMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserRoomMember, arg.RoomID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listRoomPlayers = `-- name: ListRoomPlayers :many
SELECT
  rp.room_id,
  rp.user_id,
  rp.guest_player_id,
  rp.score,
  rp.joined_at,
  COALESCE(u.username, gp.display_name)::text AS display_name,
  (rp.guest_player_id IS NOT NULL)::bool AS is_guest
FROM room_players rp
LEFT JOIN users u ON rp.user_id = u.id
LEFT JOIN guest_players gp ON rp.guest_player_id = gp.id
WHERE rp.room_id = $1
`

type ListRoomPlayersRow struct {
	RoomID        uuid.UUID   `json:"room_id"`
	UserID        pgtype.UUID `json:"user_id"`
	GuestPlayerID pgtype.UUID `json:"guest_player_id"`
	Score         int32       `json:"score"`
	JoinedAt      time.Time   `json:"joined_at"`
	DisplayName   string      `json:"display_name"`
	IsGuest       bool        `json:"is_guest"`
}

// Players in a room — unifies registered users and guests. For users,
// username comes from the users table; for guests, it comes from guest_players.
// The is_guest flag lets the frontend render a badge.
func (q *Queries) ListRoomPlayers(ctx context.Context, roomID uuid.UUID) ([]ListRoomPlayersRow, error) {
	rows, err := q.db.Query(ctx, listRoomPlayers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomPlayersRow
	for rows.Next() {
		var i ListRoomPlayersRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.GuestPlayerID,
			&i.Score,
			&i.JoinedAt,
			&i.DisplayName,
			&i.IsGuest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGuestRoomPlayer = `-- name: RemoveGuestRoomPlayer :exec
DELETE FROM room_players WHERE room_id = $1 AND guest_player_id = $2
`

type RemoveGuestRoomPlayerParams struct {
	RoomID        uuid.UUID   `json:"room_id"`
	GuestPlayerID pgtype.UUID `json:"guest_player_id"`
}

func (q *Queries) RemoveGuestRoomPlayer(ctx context.Context, arg RemoveGuestRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, removeGuestRoomPlayer, arg.RoomID, arg.GuestPlayerID)
	return err
}

const removeRoomPlayer = `-- name: RemoveRoomPlayer :exec
DELETE FROM room_players WHERE room_id = $1 AND user_id = $2
`

type RemoveRoomPlayerParams struct {
	RoomID uuid.UUID   `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveRoomPlayer(ctx context.Context, arg RemoveRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, removeRoomPlayer, arg.RoomID, arg.UserID)
	return err
}

const setRoomState = `-- name: SetRoomState :one
UPDATE rooms SET state = $2, finished_at = CASE WHEN $2 = 'finished' THEN now() ELSE NULL END
WHERE id = $1 RETURNING id, code, game_type_id, pack_id, host_id, mode, state, config, created_at, finished_at, rematch_window_expires_at, text_pack_id
`

type SetRoomStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) SetRoomState(ctx context.Context, arg SetRoomStateParams) (Room, error) {
	row := q.db.QueryRow(ctx, setRoomState, arg.ID, arg.State)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameTypeID,
		&i.PackID,
		&i.HostID,
		&i.Mode,
		&i.State,
		&i.Config,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.RematchWindowExpiresAt,
		&i.TextPackID,
	)
	return i, err
}

const startRound = `-- name: StartRound :one
UPDATE rounds SET started_at = now() WHERE id = $1 RETURNING id, room_id, item_id, round_number, started_at, ended_at
`

func (q *Queries) StartRound(ctx context.Context, id uuid.UUID) (Round, error) {
	row := q.db.QueryRow(ctx, startRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ItemID,
		&i.RoundNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const updateGuestPlayerScore = `-- name: UpdateGuestPlayerScore :one
UPDATE room_players SET score = score + $3
 WHERE room_id = $1 AND guest_player_id = $2
 RETURNING room_id, user_id, score, joined_at, guest_player_id
`

type UpdateGuestPlayerScoreParams struct {
	RoomID        uuid.UUID   `json:"room_id"`
	GuestPlayerID pgtype.UUID `json:"guest_player_id"`
	Score         int32       `json:"score"`
}

func (q *Queries) UpdateGuestPlayerScore(ctx context.Context, arg UpdateGuestPlayerScoreParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, updateGuestPlayerScore, arg.RoomID, arg.GuestPlayerID, arg.Score)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
		&i.GuestPlayerID,
	)
	return i, err
}

const updatePlayerScore = `-- name: UpdatePlayerScore :one
UPDATE room_players SET score = score + $3
 WHERE room_id = $1 AND user_id = $2
 RETURNING room_id, user_id, score, joined_at, guest_player_id
`

type UpdatePlayerScoreParams struct {
	RoomID uuid.UUID   `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
	Score  int32       `json:"score"`
}

func (q *Queries) UpdatePlayerScore(ctx context.Context, arg UpdatePlayerScoreParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, updatePlayerScore, arg.RoomID, arg.UserID, arg.Score)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
		&i.GuestPlayerID,
	)
	return i, err
}

const updateRoomConfig = `-- name: UpdateRoomConfig :one
UPDATE rooms SET config = $2 WHERE id = $1 AND state = 'lobby' RETURNING id, code, game_type_id, pack_id, host_id, mode, state, config, created_at, finished_at, rematch_window_expires_at, text_pack_id
`

type UpdateRoomConfigParams struct {
	ID     uuid.UUID       `json:"id"`
	Config json.RawMessage `json:"config"`
}

func (q *Queries) UpdateRoomConfig(ctx context.Context, arg UpdateRoomConfigParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomConfig, arg.ID, arg.Config)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameTypeID,
		&i.PackID,
		&i.HostID,
		&i.Mode,
		&i.State,
		&i.Config,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.RematchWindowExpiresAt,
		&i.TextPackID,
	)
	return i, err
}

const upsertRoomPlayer = `-- name: UpsertRoomPlayer :exec
INSERT INTO room_players (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT (room_id, user_id) WHERE user_id IS NOT NULL DO NOTHING
`

type UpsertRoomPlayerParams struct {
	RoomID uuid.UUID   `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Idempotent insert used by the hub (handleRegister) and RoomHandler.Create
// so a registered user's participation is persisted exactly once per room.
// Relies on the partial unique index room_players_user_unique from migration
// 004; guests are not reachable via this query because user_id is NOT NULL.
func (q *Queries) UpsertRoomPlayer(ctx context.Context, arg UpsertRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, upsertRoomPlayer, arg.RoomID, arg.UserID)
	return err
}
