// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_packs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteRoomPacks = `-- name: DeleteRoomPacks :exec
DELETE FROM room_packs WHERE room_id = $1
`

// Used when PATCH /api/rooms/{code}/config rewrites the pack mix in lobby.
// Followed by N InsertRoomPack calls in the same transaction.
func (q *Queries) DeleteRoomPacks(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoomPacks, roomID)
	return err
}

const insertRoomPack = `-- name: InsertRoomPack :exec

INSERT INTO room_packs (room_id, role, pack_id, weight)
VALUES ($1, $2, $3, $4)
`

type InsertRoomPackParams struct {
	RoomID uuid.UUID `json:"room_id"`
	Role   string    `json:"role"`
	PackID uuid.UUID `json:"pack_id"`
	Weight int32     `json:"weight"`
}

// backend/db/queries/room_packs.sql
func (q *Queries) InsertRoomPack(ctx context.Context, arg InsertRoomPackParams) error {
	_, err := q.db.Exec(ctx, insertRoomPack,
		arg.RoomID,
		arg.Role,
		arg.PackID,
		arg.Weight,
	)
	return err
}

const listRoomPacks = `-- name: ListRoomPacks :many
SELECT rp.role, rp.pack_id, rp.weight, gp.name AS pack_name, gp.language AS pack_language
FROM room_packs rp
JOIN game_packs gp ON rp.pack_id = gp.id
WHERE rp.room_id = $1
ORDER BY rp.role, rp.weight DESC, rp.pack_id
`

type ListRoomPacksRow struct {
	Role         string    `json:"role"`
	PackID       uuid.UUID `json:"pack_id"`
	Weight       int32     `json:"weight"`
	PackName     string    `json:"pack_name"`
	PackLanguage string    `json:"pack_language"`
}

// Every (role, pack_id, weight) tuple for a room. Joined with game_packs so
// callers that need the pack name (lobby UI, replay header) avoid a second
// round-trip. Ordered by role then weight so the heaviest pack per role is
// the first row of its group — useful for "primary mix" UI display.
func (q *Queries) ListRoomPacks(ctx context.Context, roomID uuid.UUID) ([]ListRoomPacksRow, error) {
	rows, err := q.db.Query(ctx, listRoomPacks, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomPacksRow
	for rows.Next() {
		var i ListRoomPacksRow
		if err := rows.Scan(
			&i.Role,
			&i.PackID,
			&i.Weight,
			&i.PackName,
			&i.PackLanguage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
