// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: rooms.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomPlayer = `-- name: AddRoomPlayer :one
INSERT INTO room_players (room_id, user_id) VALUES ($1, $2) RETURNING room_id, user_id, score, joined_at
`

type AddRoomPlayerParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddRoomPlayer(ctx context.Context, arg AddRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, addRoomPlayer, arg.RoomID, arg.UserID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one

INSERT INTO rooms (code, game_type_id, pack_id, host_id, mode, config)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, game_type_id, pack_id, host_id, mode, state, config, created_at, finished_at
`

type CreateRoomParams struct {
	Code       string          `json:"code"`
	GameTypeID uuid.UUID       `json:"game_type_id"`
	PackID     uuid.UUID       `json:"pack_id"`
	HostID     uuid.UUID       `json:"host_id"`
	Mode       string          `json:"mode"`
	Config     json.RawMessage `json:"config"`
}

// backend/db/queries/rooms.sql
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Code,
		arg.GameTypeID,
		arg.PackID,
		arg.HostID,
		arg.Mode,
		arg.Config,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameTypeID,
		&i.PackID,
		&i.HostID,
		&i.Mode,
		&i.State,
		&i.Config,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (room_id, item_id, round_number)
SELECT $1, $2, COALESCE(MAX(round_number), 0) + 1 FROM rounds WHERE room_id = $1
RETURNING id, room_id, item_id, round_number, started_at, ended_at
`

type CreateRoundParams struct {
	RoomID uuid.UUID `json:"room_id"`
	ItemID uuid.UUID `json:"item_id"`
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, createRound, arg.RoomID, arg.ItemID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ItemID,
		&i.RoundNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (round_id, user_id, payload) VALUES ($1, $2, $3) RETURNING id, round_id, user_id, payload, created_at
`

type CreateSubmissionParams struct {
	RoundID uuid.UUID       `json:"round_id"`
	UserID  uuid.UUID       `json:"user_id"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission, arg.RoundID, arg.UserID, arg.Payload)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.UserID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createVote = `-- name: CreateVote :one
INSERT INTO votes (submission_id, voter_id, value) VALUES ($1, $2, $3) RETURNING id, submission_id, voter_id, value, created_at
`

type CreateVoteParams struct {
	SubmissionID uuid.UUID       `json:"submission_id"`
	VoterID      uuid.UUID       `json:"voter_id"`
	Value        json.RawMessage `json:"value"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote, arg.SubmissionID, arg.VoterID, arg.Value)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.VoterID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const endRound = `-- name: EndRound :one
UPDATE rounds SET ended_at = now() WHERE id = $1 RETURNING id, room_id, item_id, round_number, started_at, ended_at
`

func (q *Queries) EndRound(ctx context.Context, id uuid.UUID) (Round, error) {
	row := q.db.QueryRow(ctx, endRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ItemID,
		&i.RoundNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const finishAbandonedLobbies = `-- name: FinishAbandonedLobbies :exec
UPDATE rooms SET state = 'finished', finished_at = now()
WHERE state = 'lobby' AND created_at < now() - interval '24 hours'
`

func (q *Queries) FinishAbandonedLobbies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, finishAbandonedLobbies)
	return err
}

const finishCrashedRooms = `-- name: FinishCrashedRooms :exec
UPDATE rooms SET state = 'finished', finished_at = now() WHERE state = 'playing'
`

func (q *Queries) FinishCrashedRooms(ctx context.Context) error {
	_, err := q.db.Exec(ctx, finishCrashedRooms)
	return err
}

const getCurrentRound = `-- name: GetCurrentRound :one
SELECT id, room_id, item_id, round_number, started_at, ended_at FROM rounds WHERE room_id = $1 AND started_at IS NOT NULL AND ended_at IS NULL
ORDER BY round_number DESC LIMIT 1
`

func (q *Queries) GetCurrentRound(ctx context.Context, roomID uuid.UUID) (Round, error) {
	row := q.db.QueryRow(ctx, getCurrentRound, roomID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ItemID,
		&i.RoundNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT r.id, r.code, r.game_type_id, r.pack_id, r.host_id, r.mode, r.state, r.config, r.created_at, r.finished_at, gt.slug AS game_type_slug FROM rooms r
JOIN game_types gt ON r.game_type_id = gt.id
WHERE r.code = $1
`

type GetRoomByCodeRow struct {
	ID           uuid.UUID          `json:"id"`
	Code         string             `json:"code"`
	GameTypeID   uuid.UUID          `json:"game_type_id"`
	PackID       uuid.UUID          `json:"pack_id"`
	HostID       uuid.UUID          `json:"host_id"`
	Mode         string             `json:"mode"`
	State        string             `json:"state"`
	Config       json.RawMessage    `json:"config"`
	CreatedAt    time.Time          `json:"created_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	GameTypeSlug string             `json:"game_type_slug"`
}

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (GetRoomByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i GetRoomByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameTypeID,
		&i.PackID,
		&i.HostID,
		&i.Mode,
		&i.State,
		&i.Config,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.GameTypeSlug,
	)
	return i, err
}

const getRoomPlayer = `-- name: GetRoomPlayer :one
SELECT room_id, user_id, score, joined_at FROM room_players WHERE room_id = $1 AND user_id = $2
`

type GetRoomPlayerParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRoomPlayer(ctx context.Context, arg GetRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, getRoomPlayer, arg.RoomID, arg.UserID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
	)
	return i, err
}

const getSubmissionsForRound = `-- name: GetSubmissionsForRound :many
SELECT id, round_id, user_id, payload, created_at FROM submissions WHERE round_id = $1
`

func (q *Queries) GetSubmissionsForRound(ctx context.Context, roundID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, getSubmissionsForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.UserID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteByVoterInRound = `-- name: GetVoteByVoterInRound :one
SELECT v.id, v.submission_id, v.voter_id, v.value, v.created_at FROM votes v
JOIN submissions s ON v.submission_id = s.id
WHERE s.round_id = $1 AND v.voter_id = $2
`

type GetVoteByVoterInRoundParams struct {
	RoundID uuid.UUID `json:"round_id"`
	VoterID uuid.UUID `json:"voter_id"`
}

func (q *Queries) GetVoteByVoterInRound(ctx context.Context, arg GetVoteByVoterInRoundParams) (Vote, error) {
	row := q.db.QueryRow(ctx, getVoteByVoterInRound, arg.RoundID, arg.VoterID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.VoterID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getVotesForRound = `-- name: GetVotesForRound :many
SELECT v.id, v.submission_id, v.voter_id, v.value, v.created_at FROM votes v
JOIN submissions s ON v.submission_id = s.id
WHERE s.round_id = $1
`

func (q *Queries) GetVotesForRound(ctx context.Context, roundID uuid.UUID) ([]Vote, error) {
	rows, err := q.db.Query(ctx, getVotesForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.VoterID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomPlayers = `-- name: ListRoomPlayers :many
SELECT rp.room_id, rp.user_id, rp.score, rp.joined_at, u.username FROM room_players rp
JOIN users u ON rp.user_id = u.id
WHERE rp.room_id = $1
`

type ListRoomPlayersRow struct {
	RoomID   uuid.UUID `json:"room_id"`
	UserID   uuid.UUID `json:"user_id"`
	Score    int32     `json:"score"`
	JoinedAt time.Time `json:"joined_at"`
	Username string    `json:"username"`
}

func (q *Queries) ListRoomPlayers(ctx context.Context, roomID uuid.UUID) ([]ListRoomPlayersRow, error) {
	rows, err := q.db.Query(ctx, listRoomPlayers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomPlayersRow
	for rows.Next() {
		var i ListRoomPlayersRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Score,
			&i.JoinedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomPlayer = `-- name: RemoveRoomPlayer :exec
DELETE FROM room_players WHERE room_id = $1 AND user_id = $2
`

type RemoveRoomPlayerParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveRoomPlayer(ctx context.Context, arg RemoveRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, removeRoomPlayer, arg.RoomID, arg.UserID)
	return err
}

const setRoomState = `-- name: SetRoomState :one
UPDATE rooms SET state = $2, finished_at = CASE WHEN $2 = 'finished' THEN now() ELSE NULL END
WHERE id = $1 RETURNING id, code, game_type_id, pack_id, host_id, mode, state, config, created_at, finished_at
`

type SetRoomStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) SetRoomState(ctx context.Context, arg SetRoomStateParams) (Room, error) {
	row := q.db.QueryRow(ctx, setRoomState, arg.ID, arg.State)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameTypeID,
		&i.PackID,
		&i.HostID,
		&i.Mode,
		&i.State,
		&i.Config,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const startRound = `-- name: StartRound :one
UPDATE rounds SET started_at = now() WHERE id = $1 RETURNING id, room_id, item_id, round_number, started_at, ended_at
`

func (q *Queries) StartRound(ctx context.Context, id uuid.UUID) (Round, error) {
	row := q.db.QueryRow(ctx, startRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ItemID,
		&i.RoundNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const updatePlayerScore = `-- name: UpdatePlayerScore :one
UPDATE room_players SET score = score + $3 WHERE room_id = $1 AND user_id = $2 RETURNING room_id, user_id, score, joined_at
`

type UpdatePlayerScoreParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
	Score  int32     `json:"score"`
}

func (q *Queries) UpdatePlayerScore(ctx context.Context, arg UpdatePlayerScoreParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, updatePlayerScore, arg.RoomID, arg.UserID, arg.Score)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
	)
	return i, err
}

const updateRoomConfig = `-- name: UpdateRoomConfig :one
UPDATE rooms SET config = $2 WHERE id = $1 AND state = 'lobby' RETURNING id, code, game_type_id, pack_id, host_id, mode, state, config, created_at, finished_at
`

type UpdateRoomConfigParams struct {
	ID     uuid.UUID       `json:"id"`
	Config json.RawMessage `json:"config"`
}

func (q *Queries) UpdateRoomConfig(ctx context.Context, arg UpdateRoomConfigParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomConfig, arg.ID, arg.Config)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameTypeID,
		&i.PackID,
		&i.HostID,
		&i.Mode,
		&i.State,
		&i.Config,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
