// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_invite_quotas.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeUserInviteQuota = `-- name: ConsumeUserInviteQuota :one
UPDATE user_invite_quotas
SET used = used + 1, updated_at = now()
WHERE user_id = $1 AND used < allocated
RETURNING user_id, allocated, used, updated_at
`

// Atomic decrement-by-incrementing-used at platform+group invite mint time.
// Returns no row (sql.ErrNoRows) when the user is at or above their cap, so
// the handler maps that to platform_plus_quota_exhausted. We do NOT
// pre-create a row here — admins must explicitly allocate a quota first.
func (q *Queries) ConsumeUserInviteQuota(ctx context.Context, userID uuid.UUID) (UserInviteQuota, error) {
	row := q.db.QueryRow(ctx, consumeUserInviteQuota, userID)
	var i UserInviteQuota
	err := row.Scan(
		&i.UserID,
		&i.Allocated,
		&i.Used,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeUserInviteQuotaN = `-- name: ConsumeUserInviteQuotaN :one
UPDATE user_invite_quotas
SET used = used + $1::int, updated_at = now()
WHERE user_id = $2::uuid AND used + $1::int <= allocated
RETURNING user_id, allocated, used, updated_at
`

type ConsumeUserInviteQuotaNParams struct {
	Amount int32     `json:"amount"`
	UserID uuid.UUID `json:"user_id"`
}

// Multi-slot variant for multi-use platform+group invites. The mint debits
// max_uses slots upfront so the admin cannot mint a 50-use code from a
// 1-slot allowance. Same return-no-row contract as the single-slot version
// when the requested debit would exceed the user's cap.
func (q *Queries) ConsumeUserInviteQuotaN(ctx context.Context, arg ConsumeUserInviteQuotaNParams) (UserInviteQuota, error) {
	row := q.db.QueryRow(ctx, consumeUserInviteQuotaN, arg.Amount, arg.UserID)
	var i UserInviteQuota
	err := row.Scan(
		&i.UserID,
		&i.Allocated,
		&i.Used,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureUserInviteQuotaRow = `-- name: EnsureUserInviteQuotaRow :exec
INSERT INTO user_invite_quotas (user_id, allocated, used)
VALUES ($1, $2, 0)
ON CONFLICT (user_id) DO NOTHING
`

type EnsureUserInviteQuotaRowParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Allocated int32     `json:"allocated"`
}

// Idempotent first-touch row insert used by the lazy-default flow: if the
// maker has never had quota explicitly set by a platform admin, the mint
// handler creates a row at DEFAULT_PLATFORM_PLUS_QUOTA on their first
// attempt so non-admins can self-serve a small allowance without operator
// intervention. ON CONFLICT DO NOTHING preserves any admin-set allocation —
// this never overwrites a row the admin had already tuned up or down.
func (q *Queries) EnsureUserInviteQuotaRow(ctx context.Context, arg EnsureUserInviteQuotaRowParams) error {
	_, err := q.db.Exec(ctx, ensureUserInviteQuotaRow, arg.UserID, arg.Allocated)
	return err
}

const getUserInviteQuota = `-- name: GetUserInviteQuota :one
SELECT user_id, allocated, used, updated_at FROM user_invite_quotas WHERE user_id = $1
`

func (q *Queries) GetUserInviteQuota(ctx context.Context, userID uuid.UUID) (UserInviteQuota, error) {
	row := q.db.QueryRow(ctx, getUserInviteQuota, userID)
	var i UserInviteQuota
	err := row.Scan(
		&i.UserID,
		&i.Allocated,
		&i.Used,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserInviteQuotas = `-- name: ListUserInviteQuotas :many
SELECT q.user_id, q.allocated, q.used, q.updated_at, u.username, u.email
FROM user_invite_quotas q
JOIN users u ON u.id = q.user_id
ORDER BY u.username ASC
`

type ListUserInviteQuotasRow struct {
	UserID    uuid.UUID `json:"user_id"`
	Allocated int32     `json:"allocated"`
	Used      int32     `json:"used"`
	UpdatedAt time.Time `json:"updated_at"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
}

// Admin overview: every user that has a quota row, alphabetised by username
// so the table is stable across renders.
func (q *Queries) ListUserInviteQuotas(ctx context.Context) ([]ListUserInviteQuotasRow, error) {
	rows, err := q.db.Query(ctx, listUserInviteQuotas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserInviteQuotasRow
	for rows.Next() {
		var i ListUserInviteQuotasRow
		if err := rows.Scan(
			&i.UserID,
			&i.Allocated,
			&i.Used,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserInviteQuota = `-- name: UpsertUserInviteQuota :one

INSERT INTO user_invite_quotas (user_id, allocated, used)
VALUES ($1, $2, 0)
ON CONFLICT (user_id) DO UPDATE
SET allocated = EXCLUDED.allocated, updated_at = now()
RETURNING user_id, allocated, used, updated_at
`

type UpsertUserInviteQuotaParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Allocated int32     `json:"allocated"`
}

// backend/db/queries/user_invite_quotas.sql
//
// Per-user platform+group invite allocation. Set by the platform admin;
// consumed when a user mints a platform+group invite (phase 2). The CHECK
// (used <= allocated) constraint defends against admin lowering allocation
// below current consumption — the handler maps the resulting pg error to
// a 409.
func (q *Queries) UpsertUserInviteQuota(ctx context.Context, arg UpsertUserInviteQuotaParams) (UserInviteQuota, error) {
	row := q.db.QueryRow(ctx, upsertUserInviteQuota, arg.UserID, arg.Allocated)
	var i UserInviteQuota
	err := row.Scan(
		&i.UserID,
		&i.Allocated,
		&i.Used,
		&i.UpdatedAt,
	)
	return i, err
}
