// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmEmailChange = `-- name: ConfirmEmailChange :one
UPDATE users SET email = pending_email, pending_email = NULL WHERE id = $1 RETURNING id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected
`

func (q *Queries) ConfirmEmailChange(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, confirmEmailChange, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE id != '00000000-0000-0000-0000-000000000001'
  AND (lower(username) LIKE lower('%' || $1 || '%')
       OR lower(email) LIKE lower('%' || $1 || '%'))
`

// Matches ListUsers' sentinel exclusion so the admin dashboard count and
// table row count always agree.
func (q *Queries) CountUsers(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, role, is_active, invited_by, consent_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected
`

type CreateUserParams struct {
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	Role      string      `json:"role"`
	IsActive  bool        `json:"is_active"`
	InvitedBy pgtype.UUID `json:"invited_by"`
	ConsentAt time.Time   `json:"consent_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.IsActive,
		arg.InvitedBy,
		arg.ConsentAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const getSentinelUser = `-- name: GetSentinelUser :one

SELECT id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected FROM users WHERE id = '00000000-0000-0000-0000-000000000001'
`

// Sentinel UUID: 00000000-0000-0000-0000-000000000001 (see auth.SentinelUserID in Go).
// Used to anonymize submissions/votes on hard-delete without breaking referential integrity.
func (q *Queries) GetSentinelUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getSentinelUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected FROM users WHERE id = $1
`

// backend/db/queries/users.sql
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const getUserGameHistory = `-- name: GetUserGameHistory :many
SELECT
  r.code,
  gt.slug AS game_type_slug,
  gp.name AS pack_name,
  r.created_at AS started_at,
  r.finished_at,
  rp.score,
  r.id AS room_id,
  ((SELECT COUNT(*) FROM room_players rp2 WHERE rp2.room_id = r.id AND rp2.score > rp.score) + 1)::bigint AS rank,
  (SELECT COUNT(*) FROM room_players rp3 WHERE rp3.room_id = r.id) AS player_count
FROM room_players rp
JOIN rooms r ON rp.room_id = r.id
JOIN game_types gt ON r.game_type_id = gt.id
JOIN game_packs gp ON r.pack_id = gp.id
WHERE rp.user_id = $1 AND r.state = 'finished'
ORDER BY r.finished_at DESC NULLS LAST
LIMIT $3 OFFSET $2
`

type GetUserGameHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Off    int32       `json:"off"`
	Lim    int32       `json:"lim"`
}

type GetUserGameHistoryRow struct {
	Code         string             `json:"code"`
	GameTypeSlug string             `json:"game_type_slug"`
	PackName     string             `json:"pack_name"`
	StartedAt    time.Time          `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	Score        int32              `json:"score"`
	RoomID       uuid.UUID          `json:"room_id"`
	Rank         int64              `json:"rank"`
	PlayerCount  int64              `json:"player_count"`
}

func (q *Queries) GetUserGameHistory(ctx context.Context, arg GetUserGameHistoryParams) ([]GetUserGameHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUserGameHistory, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGameHistoryRow
	for rows.Next() {
		var i GetUserGameHistoryRow
		if err := rows.Scan(
			&i.Code,
			&i.GameTypeSlug,
			&i.PackName,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Score,
			&i.RoomID,
			&i.Rank,
			&i.PlayerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubmissions = `-- name: GetUserSubmissions :many
SELECT
  s.id,
  s.round_id,
  r2.code AS room_code,
  gt.slug AS game_type_slug,
  s.payload,
  s.created_at
FROM submissions s
JOIN rounds rnd ON s.round_id = rnd.id
JOIN rooms r2 ON rnd.room_id = r2.id
JOIN game_types gt ON r2.game_type_id = gt.id
WHERE s.user_id = $1
  AND r2.state = 'finished'
ORDER BY s.created_at DESC
`

type GetUserSubmissionsRow struct {
	ID           uuid.UUID       `json:"id"`
	RoundID      uuid.UUID       `json:"round_id"`
	RoomCode     string          `json:"room_code"`
	GameTypeSlug string          `json:"game_type_slug"`
	Payload      json.RawMessage `json:"payload"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) GetUserSubmissions(ctx context.Context, userID pgtype.UUID) ([]GetUserSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserSubmissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSubmissionsRow
	for rows.Next() {
		var i GetUserSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.RoomCode,
			&i.GameTypeSlug,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsernamesByIDs = `-- name: GetUsernamesByIDs :many
SELECT id, username FROM users WHERE id = ANY($1::uuid[])
`

type GetUsernamesByIDsRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

// Batch lookup for the audit-log enrichment path. Returns only id + username
// so the admin dashboard can resolve "user:<uuid>" audit resources without
// paying for full user rows.
func (q *Queries) GetUsernamesByIDs(ctx context.Context, ids []uuid.UUID) ([]GetUsernamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsernamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsernamesByIDsRow
	for rows.Next() {
		var i GetUsernamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) HardDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT
  u.id,
  u.username,
  u.email,
  u.pending_email,
  u.role,
  u.is_active,
  u.invited_by,
  u.consent_at,
  u.created_at,
  u.is_protected,
  COALESCE((
    SELECT COUNT(*)
    FROM room_players rp
    JOIN rooms r ON r.id = rp.room_id
    WHERE rp.user_id = u.id AND r.state = 'finished'
  ), 0)::bigint AS games_played,
  (SELECT MAX(s.created_at) FROM sessions s WHERE s.user_id = u.id) AS last_login_at
FROM users u
WHERE u.id != '00000000-0000-0000-0000-000000000001'
  AND (lower(u.username) LIKE lower('%' || $1 || '%')
       OR lower(u.email) LIKE lower('%' || $1 || '%'))
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $2
`

type ListUsersParams struct {
	Search *string `json:"search"`
	Off    int32   `json:"off"`
	Lim    int32   `json:"lim"`
}

type ListUsersRow struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PendingEmail *string            `json:"pending_email"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	InvitedBy    pgtype.UUID        `json:"invited_by"`
	ConsentAt    time.Time          `json:"consent_at"`
	CreatedAt    time.Time          `json:"created_at"`
	IsProtected  bool               `json:"is_protected"`
	GamesPlayed  int64              `json:"games_played"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

// Excludes the GDPR sentinel row (see SentinelUserID). The sentinel is a
// data-integrity placeholder, never a real account, so it must not appear
// in admin tooling or counts.
//
// games_played: count of finished rooms this user was a player in. Scoped
// to state='finished' so lobby/in-progress rooms don't inflate the figure.
//
// last_login_at: MAX(sessions.created_at). Sessions are deleted on logout,
// so this is "most recent live-login timestamp" — NULL for users who are
// fully logged out. Good enough as a health signal without schema churn;
// graduate to a dedicated users.last_login_at column if accuracy matters.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PendingEmail,
			&i.Role,
			&i.IsActive,
			&i.InvitedBy,
			&i.ConsentAt,
			&i.CreatedAt,
			&i.IsProtected,
			&i.GamesPlayed,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPendingEmail = `-- name: SetPendingEmail :one
UPDATE users SET pending_email = $2 WHERE id = $1 RETURNING id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected
`

type SetPendingEmailParams struct {
	ID           uuid.UUID `json:"id"`
	PendingEmail *string   `json:"pending_email"`
}

func (q *Queries) SetPendingEmail(ctx context.Context, arg SetPendingEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, setPendingEmail, arg.ID, arg.PendingEmail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users SET is_active = $2 WHERE id = $1 RETURNING id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected
`

type SetUserActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const setUserProtected = `-- name: SetUserProtected :exec
UPDATE users SET is_protected = $2 WHERE id = $1
`

type SetUserProtectedParams struct {
	ID          uuid.UUID `json:"id"`
	IsProtected bool      `json:"is_protected"`
}

// Toggles the is_protected flag. Called exclusively by auth.SeedAdmin to
// stamp the bootstrap admin. There is deliberately no handler that flips
// this from the admin API — protection is a runtime-immutable property.
func (q *Queries) SetUserProtected(ctx context.Context, arg SetUserProtectedParams) error {
	_, err := q.db.Exec(ctx, setUserProtected, arg.ID, arg.IsProtected)
	return err
}

const updateSubmissionsSentinel = `-- name: UpdateSubmissionsSentinel :exec
UPDATE submissions SET user_id = '00000000-0000-0000-0000-000000000001' WHERE user_id = $1
`

func (q *Queries) UpdateSubmissionsSentinel(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSubmissionsSentinel, userID)
	return err
}

const updateUserEmailAdmin = `-- name: UpdateUserEmailAdmin :one
UPDATE users SET email = $2 WHERE id = $1 RETURNING id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected
`

type UpdateUserEmailAdminParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) UpdateUserEmailAdmin(ctx context.Context, arg UpdateUserEmailAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmailAdmin, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2 WHERE id = $1 RETURNING id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const updateUserUsername = `-- name: UpdateUserUsername :one
UPDATE users SET username = $2 WHERE id = $1 RETURNING id, username, email, pending_email, role, is_active, invited_by, consent_at, created_at, is_protected
`

type UpdateUserUsernameParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Role,
		&i.IsActive,
		&i.InvitedBy,
		&i.ConsentAt,
		&i.CreatedAt,
		&i.IsProtected,
	)
	return i, err
}

const updateVotesSentinel = `-- name: UpdateVotesSentinel :exec
UPDATE votes SET voter_id = '00000000-0000-0000-0000-000000000001' WHERE voter_id = $1
`

func (q *Queries) UpdateVotesSentinel(ctx context.Context, voterID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateVotesSentinel, voterID)
	return err
}
